import "server-only";
import nodemailer from "nodemailer";

export interface SmtpConfig {host:string;port:number;secure:boolean;user?:string;password?:string;from:string}
const escapeHtml=(value:string)=>value.replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]!);
export function mailer(config:SmtpConfig){return nodemailer.createTransport({host:config.host,port:config.port,secure:config.secure,auth:config.user?{user:config.user,pass:config.password}:undefined,connectionTimeout:10000,socketTimeout:15000})}
export async function sendSafeNotification(config:SmtpConfig,to:string,subject:string,message:string,actionUrl:string,actionLabel="Finanzplaner öffnen"){
  const safeSubject=escapeHtml(subject),safeMessage=escapeHtml(message),safeUrl=escapeHtml(actionUrl),safeLabel=escapeHtml(actionLabel);
  const html=`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f3f7f7;font-family:Arial,sans-serif;color:#183436"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f3f7f7;padding:32px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;background:#ffffff;border-radius:20px;overflow:hidden;box-shadow:0 8px 30px rgba(22,64,67,.10)"><tr><td style="padding:28px 32px;background:linear-gradient(135deg,#136f78,#20b486);color:#ffffff"><div style="font-size:13px;font-weight:bold;letter-spacing:.12em;text-transform:uppercase">Finanzplaner</div><h1 style="margin:10px 0 0;font-size:26px;line-height:1.25">${safeSubject}</h1></td></tr><tr><td style="padding:32px"><p style="margin:0 0 24px;font-size:16px;line-height:1.65">${safeMessage}</p><table role="presentation" cellspacing="0" cellpadding="0"><tr><td style="border-radius:12px;background:#136f78"><a href="${safeUrl}" style="display:inline-block;padding:14px 22px;color:#ffffff;text-decoration:none;font-size:16px;font-weight:bold">${safeLabel}</a></td></tr></table><p style="margin:26px 0 8px;font-size:13px;line-height:1.5;color:#627778">Falls die Schaltfläche nicht funktioniert, kopiere diesen Link in den Browser:</p><p style="margin:0;word-break:break-all;font-size:13px;line-height:1.5"><a href="${safeUrl}" style="color:#136f78">${safeUrl}</a></p></td></tr><tr><td style="padding:20px 32px;background:#edf5f3;color:#627778;font-size:12px;line-height:1.5">Diese Nachricht enthält bewusst keine Finanzdaten. Der Finanzplaner wird ausschließlich in deinem lokalen Netzwerk betrieben.</td></tr></table></td></tr></table></body></html>`;
  return mailer(config).sendMail({from:config.from,to,subject,text:`${message}\n\n${actionLabel}: ${actionUrl}\n\nDiese Nachricht enthält bewusst keine Finanzdaten.`,html});
}
