import { NextResponse } from "next/server";
import { and, desc, eq, gte, inArray, sql } from "drizzle-orm";
import { db } from "@/db";
import { accounts, categories, recurringTransactions, transactions } from "@/db/schema";
import { classifyRecurringPayment, detectRecurring, normalizeRecurringMerchant } from "@/features/analytics/recurring";
import { requireUser } from "@/lib/current-user";
import { memberAndVisibleAccountIds } from "@/lib/visible-accounts";
import { writeAudit } from "@/lib/audit";

export async function GET() {
  try {
    const user = await requireUser(); const { accountIds } = await memberAndVisibleAccountIds(user.userId);
    if(!accountIds.length)return NextResponse.json([]);
    const from=new Date();from.setUTCMonth(from.getUTCMonth()-14);
    const [rows,saved]=await Promise.all([db.select({id:transactions.id,accountId:transactions.accountId,bookedOn:transactions.bookedOn,amount:transactions.amount,merchant:transactions.counterparty,categoryName:categories.name,accountName:accounts.name})
      .from(transactions).innerJoin(accounts,eq(transactions.accountId,accounts.id)).leftJoin(categories,eq(transactions.categoryId,categories.id))
      .where(and(inArray(transactions.accountId,accountIds),eq(transactions.direction,"expense"),eq(transactions.excludedFromAnalysis,false),gte(transactions.bookedOn,from.toISOString().slice(0,10)),sql`${transactions.amount} <> 0`)).orderBy(desc(transactions.bookedOn)),db.select({accountId:recurringTransactions.accountId,merchantPattern:recurringTransactions.merchantPattern,status:recurringTransactions.status,kind:recurringTransactions.kind}).from(recurringTransactions).where(inArray(recurringTransactions.accountId,accountIds))]);
    const ignored=new Set(saved.filter(item=>item.status==="dismissed").map(item=>`${item.accountId}|${item.merchantPattern}`));
    const overrides=new Map(saved.filter(item=>item.status==="confirmed").map(item=>[`${item.accountId}|${item.merchantPattern}`,item.kind]));
    const candidates=accountIds.flatMap(accountId=>detectRecurring(rows.filter(row=>row.accountId===accountId).map(row=>({id:row.id,bookedOn:row.bookedOn,amount:Number(row.amount),merchant:row.merchant??""}))).map(candidate=>({...candidate,accountId}))).filter(candidate=>!ignored.has(`${candidate.accountId}|${normalizeRecurringMerchant(candidate.merchant)}`));
    const byId=new Map(rows.map(row=>[row.id,row]));
    return NextResponse.json(candidates.map(candidate=>{const latest=byId.get(candidate.transactionIds.at(-1)!);const key=`${candidate.accountId}|${normalizeRecurringMerchant(candidate.merchant)}`;return{...candidate,lastSeenOn:latest?.bookedOn,categoryName:latest?.categoryName??"Nicht zugeordnet",accountName:latest?.accountName??"",cadence:candidate.cadenceDays<10?"Wöchentlich":candidate.cadenceDays>300?"Jährlich":"Monatlich",kind:overrides.get(key)??classifyRecurringPayment(candidate.merchant,latest?.categoryName)}}));
  } catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Wiederkehrende Zahlungen konnten nicht ermittelt werden."},{status:400})}
}

export async function PATCH(request:Request){try{const user=await requireUser();const{accountIds}=await memberAndVisibleAccountIds(user.userId);const body=await request.json() as {accountId?:string;merchant?:string;kind?:"subscription"|"regular";cadenceDays?:number;averageAmount?:number;lastSeenOn?:string};if(!body.accountId||!accountIds.includes(body.accountId)||!body.merchant?.trim()||!(["subscription","regular"] as const).includes(body.kind!))throw new Error("Wiederkehrende Zahlung ist nicht sichtbar oder die Art ist ungültig.");const merchantPattern=normalizeRecurringMerchant(body.merchant);await db.delete(recurringTransactions).where(and(eq(recurringTransactions.accountId,body.accountId),eq(recurringTransactions.merchantPattern,merchantPattern)));await db.insert(recurringTransactions).values({accountId:body.accountId,merchantPattern,cadenceDays:Math.max(1,Math.round(body.cadenceDays??30)),expectedAmount:Number(body.averageAmount??0).toFixed(2),kind:body.kind!,status:"confirmed",lastSeenOn:body.lastSeenOn??new Date().toISOString().slice(0,10)});await writeAudit("recurring-classified",`Wiederkehrende Zahlung „${body.merchant}“ wurde eingeordnet.`,{userId:user.userId,metadata:{accountId:body.accountId,merchantPattern,kind:body.kind}});return NextResponse.json({ok:true})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Wiederkehrende Zahlung konnte nicht eingeordnet werden."},{status:400})}}

export async function DELETE(request:Request){try{const user=await requireUser();const{accountIds}=await memberAndVisibleAccountIds(user.userId);const body=await request.json() as {accountId?:string;merchant?:string;cadenceDays?:number;averageAmount?:number;lastSeenOn?:string};if(!body.accountId||!accountIds.includes(body.accountId)||!body.merchant?.trim())throw new Error("Wiederkehrende Zahlung ist nicht sichtbar.");const merchantPattern=normalizeRecurringMerchant(body.merchant);await db.delete(recurringTransactions).where(and(eq(recurringTransactions.accountId,body.accountId),eq(recurringTransactions.merchantPattern,merchantPattern),eq(recurringTransactions.status,"dismissed")));await db.insert(recurringTransactions).values({accountId:body.accountId,merchantPattern,cadenceDays:Math.max(1,Math.round(body.cadenceDays??30)),expectedAmount:Number(body.averageAmount??0).toFixed(2),status:"dismissed",lastSeenOn:body.lastSeenOn??new Date().toISOString().slice(0,10)});await writeAudit("recurring-dismissed",`Wiederkehrende Erkennung „${body.merchant}“ wurde ausgeblendet.`,{userId:user.userId,metadata:{accountId:body.accountId,merchantPattern}});return NextResponse.json({ok:true})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Wiederkehrende Zahlung konnte nicht gelöscht werden."},{status:400})}}
