// Name, Slug, Farbe, Icon, optionaler Eltern-Slug, Einnahme.
// Bewusst ohne Auffangkategorie: Unklare Umsätze bleiben sichtbar offen.
export const defaultCategories = [
  ["Wohnen","wohnen","#2367a1","house"],
  ["Miete","miete","#3478ad","key-round","wohnen"],
  ["Nebenkosten","nebenkosten","#3478ad","receipt-text","wohnen"],
  ["Strom","strom","#3478ad","zap","wohnen"],
  ["Heizung","heizung","#3478ad","flame","wohnen"],
  ["Instandhaltung & Renovierung","instandhaltung-renovierung","#3478ad","hammer","wohnen"],
  ["Möbel & Einrichtung","moebel-einrichtung","#3478ad","sofa","wohnen"],
  ["Lebensmittel & Getränke","lebensmittel","#087e82","shopping-basket"],
  ["Supermarkt","supermarkt","#159296","shopping-cart","lebensmittel"],
  ["Bäckerei","baeckerei","#159296","croissant","lebensmittel"],
  ["Getränke","getraenke","#159296","cup-soda","lebensmittel"],
  ["Mobilität","mobilitaet","#31a77d","car"],
  ["Tanken","tanken","#3daf87","fuel","mobilitaet"],
  ["ÖPNV & Bahn","oepnv-bahn","#3daf87","train-front","mobilitaet"],
  ["Parken & Maut","parken-maut","#3daf87","circle-parking","mobilitaet"],
  ["Wartung & Reparatur","kfz-wartung-reparatur","#3daf87","wrench","mobilitaet"],
  ["Leasing & Fahrzeugkauf","leasing-fahrzeugkauf","#3daf87","car-front","mobilitaet"],
  ["Kommunikation & Medien","kommunikation-medien","#5275a8","wifi"],
  ["Telefon & Internet","telefon-internet","#6385b5","phone","kommunikation-medien"],
  ["Streaming","streaming","#6385b5","tv","kommunikation-medien"],
  ["Software & Cloud","software-cloud","#6385b5","cloud","kommunikation-medien"],
  ["Rundfunkbeitrag","rundfunkbeitrag","#6385b5","radio","kommunikation-medien"],
  ["Haushalt & Drogerie","haushalt-drogerie","#159b94","spray-can"],
  ["Drogerie & Körperpflege","drogerie-koerperpflege","#27aaa3","sparkles","haushalt-drogerie"],
  ["Reinigung & Haushaltswaren","reinigung-haushaltswaren","#27aaa3","brush-cleaning","haushalt-drogerie"],
  ["Einkäufe","einkaeufe","#7d6da8","shopping-bag"],
  ["Kleidung & Schuhe","kleidung-schuhe","#8e7db8","shirt","einkaeufe"],
  ["Elektronik","elektronik","#8e7db8","monitor-smartphone","einkaeufe"],
  ["Bücher & Medien","buecher-medien","#8e7db8","book-open","einkaeufe"],
  ["Werkzeug & Hobbybedarf","werkzeug-hobbybedarf","#8e7db8","drill","einkaeufe"],
  ["Gesundheit","gesundheit","#c44f64","heart-pulse"],
  ["Apotheke & Medikamente","apotheke-medikamente","#cf6174","pill","gesundheit"],
  ["Arzt & Behandlung","arzt-behandlung","#cf6174","stethoscope","gesundheit"],
  ["Brille & Hilfsmittel","brille-hilfsmittel","#cf6174","glasses","gesundheit"],
  ["Versicherungen","versicherungen","#556b87","shield"],
  ["Kfz-Versicherung","kfz-versicherung","#667b96","car","versicherungen"],
  ["Haftpflicht","haftpflicht","#667b96","shield-check","versicherungen"],
  ["Hausrat & Gebäude","hausrat-gebaeude","#667b96","house","versicherungen"],
  ["Rechtsschutz","rechtsschutz","#667b96","scale","versicherungen"],
  ["Personenversicherung","personenversicherung","#667b96","heart-handshake","versicherungen"],
  ["Bank & Finanzen","bank-finanzen","#786b58","landmark"],
  ["Kontoführungsgebühren","kontofuehrungsgebuehren","#897b68","receipt","bank-finanzen"],
  ["Sollzinsen","sollzinsen","#897b68","percent","bank-finanzen"],
  ["Depot & Geldanlage","depot-geldanlage","#897b68","chart-candlestick","bank-finanzen"],
  ["Kredite & Raten","kredite-raten","#8a665a","badge-euro"],
  ["Darlehensrate","darlehensrate","#9a776b","house","kredite-raten"],
  ["Kreditkartenrate","kreditkartenrate","#9a776b","credit-card","kredite-raten"],
  ["Ratenkauf","ratenkauf","#9a776b","calendar-clock","kredite-raten"],
  ["Freizeit","freizeit","#d88a35","party-popper"],
  ["Restaurants & Cafés","restaurants-cafes","#df9849","utensils","freizeit"],
  ["Kultur & Veranstaltungen","kultur-veranstaltungen","#df9849","ticket","freizeit"],
  ["Sport & Vereine","sport-vereine","#df9849","dumbbell","freizeit"],
  ["App- & In-Game-Käufe","app-in-game","#df9849","gamepad-2","freizeit"],
  ["Hobbys","hobbys","#df9849","palette","freizeit"],
  ["Reisen & Urlaub","reisen-urlaub","#2f9eaa","plane"],
  ["Unterkunft","unterkunft","#43acb7","bed-double","reisen-urlaub"],
  ["Anreise & Mietwagen","anreise-mietwagen","#43acb7","route","reisen-urlaub"],
  ["Aktivitäten im Urlaub","urlaubsaktivitaeten","#43acb7","map","reisen-urlaub"],
  ["Familie & Kinder","familie-kinder","#d26b90","baby"],
  ["Betreuung & Schule","betreuung-schule","#db7ca0","school","familie-kinder"],
  ["Kinderkleidung","kinderkleidung","#db7ca0","shirt","familie-kinder"],
  ["Spielzeug & Taschengeld","spielzeug-taschengeld","#db7ca0","blocks","familie-kinder"],
  ["Bildung & Beruf","bildung-beruf","#6c7f52","graduation-cap"],
  ["Weiterbildung","weiterbildung","#7e9164","book-open-check","bildung-beruf"],
  ["Arbeitsmittel","arbeitsmittel","#7e9164","briefcase-business","bildung-beruf"],
  ["Steuern & Abgaben","steuern-abgaben","#9a7554","file-text"],
  ["Geschenke & Spenden","geschenke-spenden","#b05f78","gift"],
  ["Tierhaltung","tierhaltung","#84714f","paw-print"],
  ["Tierfutter & Zubehör","tierfutter-zubehoer","#958260","bone","tierhaltung"],
  ["Tierarzt","tierarzt","#958260","cross","tierhaltung"],
  ["Interne Umbuchung","umbuchung","#758387","arrow-left-right"],
  ["Einnahmen","einnahmen","#2a996b","wallet",null,true],
  ["Gehalt & Lohn","gehalt-lohn","#3baa7b","badge-euro","einnahmen",true],
  ["Kindergeld & Familienleistungen","kindergeld-familienleistungen","#3baa7b","baby","einnahmen",true],
  ["Rente & Pension","rente-pension","#3baa7b","landmark","einnahmen",true],
  ["Kapitalerträge & Habenzinsen","kapitalertraege","#3baa7b","trending-up","einnahmen",true],
  ["Erstattungen & Rückzahlungen","erstattungen-rueckzahlungen","#3baa7b","rotate-ccw","einnahmen",true],
  ["Verkäufe & Nebeneinkünfte","verkaeufe-nebeneinkuenfte","#3baa7b","hand-coins","einnahmen",true],
] as const;
