// Bewusst kleiner Startbestand ohne Auffangkategorie. Weitere Kategorien legt
// der Haushalt bei Bedarf selbst an; Updates säen diesen Bestand nie erneut.
export const defaultCategories = [
  ["Bank & Finanzen", "bank-finanzen", "#786b58", "landmark"],
  ["Kontoführungsgebühren", "kontofuehrungsgebuehren", "#897b68", "receipt", "bank-finanzen"],
  ["Kredite & Raten", "kredite-raten", "#897b68", "badge-euro", "bank-finanzen"],
  ["Familie & Kinder", "familie-kinder", "#d26b90", "baby"],
  ["Freizeit", "freizeit", "#d88a35", "party-popper"],
  ["App- & In-Game-Käufe", "app-in-game", "#df9849", "gamepad-2", "freizeit"],
  ["Restaurants & Cafés", "restaurants-cafes", "#df9849", "utensils", "freizeit"],
  ["Gesundheit", "gesundheit", "#c44f64", "heart-pulse"],
  ["Apotheke & Medikamente", "apotheke-medikamente", "#cf6174", "pill", "gesundheit"],
  ["Haushalt & Drogerie", "haushalt-drogerie", "#159b94", "spray-can"],
  ["Interne Umbuchung (nicht auswerten)", "umbuchung", "#758387", "arrow-left-right"],
  ["Kommunikation & Medien", "kommunikation-medien", "#5275a8", "wifi"],
  ["Streaming & Software", "streaming-software", "#6385b5", "tv", "kommunikation-medien"],
  ["Telefon & Internet", "telefon-internet", "#6385b5", "phone", "kommunikation-medien"],
  ["Lebensmittel", "lebensmittel", "#087e82", "shopping-basket"],
  ["Mobilität", "mobilitaet", "#31a77d", "car"],
  ["Kfz-Wartung", "kfz-wartung", "#3daf87", "wrench", "mobilitaet"],
  ["ÖPNV & Bahn", "oepnv-bahn", "#3daf87", "train-front", "mobilitaet"],
  ["Tanken", "tanken", "#3daf87", "fuel", "mobilitaet"],
  ["Reisen & Urlaub", "reisen-urlaub", "#2f9eaa", "plane"],
  ["Tierhaltung", "tierhaltung", "#84714f", "paw-print"],
  ["Versicherungen", "versicherungen", "#556b87", "shield"],
  ["Kfz-Versicherung", "kfz-versicherung", "#667b96", "car", "versicherungen"],
  ["Wohnen", "wohnen", "#2367a1", "house"],
  ["Miete", "miete", "#3478ad", "key-round", "wohnen"],
  ["Nebenkosten", "nebenkosten", "#3478ad", "receipt-text", "wohnen"],
  ["Strom & Heizung", "strom-heizung", "#3478ad", "zap", "wohnen"],
  ["Einnahmen", "einnahmen", "#2a996b", "wallet", null, true],
  ["Erstattungen", "erstattungen", "#3baa7b", "rotate-ccw", "einnahmen", true],
  ["Gehalt & Lohn", "gehalt-lohn", "#3baa7b", "badge-euro", "einnahmen", true],
  ["Kapitalerträge", "kapitalertraege", "#3baa7b", "trending-up", "einnahmen", true],
  ["Kindergeld", "kindergeld", "#3baa7b", "baby", "einnahmen", true],
] as const;
