import {createHash,randomUUID} from "node:crypto";
import {after,NextResponse} from "next/server";
import {FinTSClient,FinTSConfig,type BankingInformation,type StatementResponse} from "lib-fints";
import {and,eq,ilike} from "drizzle-orm";
import {z} from "zod";
import {db} from "@/db";
import {imports,importTemplates,systemSettings,transactions} from "@/db/schema";
import {cleanupFinTsStatementSessions,finTsStatementSessions} from "@/features/fints/pending-sessions";
import {normalizeMerchant} from "@/features/categorization/merchant-rules";
import {applyAutomaticAssignments} from "@/features/categorization/automatic-assignments";
import {findDuplicates} from "@/features/import/parser";
import type {ParsedTransaction} from "@/features/import/types";
import {requireUser} from "@/lib/current-user";
import {decryptSecret,encryptSecret} from "@/lib/security";
import {memberAndVisibleAccountIds} from "@/lib/visible-accounts";
import {writeAudit} from "@/lib/audit";
import {runHouseholdIntegrityCheck} from "@/features/integrity/service";
import {finTsProductVersion} from "@/features/fints/product-version";

type Connection={productId:string;endpoint:string;blz:string;userId:string;pin:string;tanMethodId?:number;tanMediaName?:string;bankAccountNumber:string;bankingInformation:BankingInformation};
const schema=z.discriminatedUnion("action",[z.object({action:z.literal("start"),days:z.number().int().min(1).max(365).default(90)}),z.object({action:z.literal("continue_tan"),token:z.string().uuid(),tan:z.string().max(20).optional()})]);
const date=(value:Date)=>value.toISOString().slice(0,10),clean=(value?:string)=>value?.replace(/\s+/g," ").trim(),hash=(value:string)=>createHash("sha256").update(value).digest("hex");
function parsed(response:StatementResponse):ParsedTransaction[]{return response.statements.flatMap(statement=>statement.transactions).filter(item=>Math.abs(item.amount)>=.005).map(item=>{const booked=date(item.entryDate),valued=date(item.valueDate),counterparty=clean(item.remoteName),purpose=clean(item.purpose??item.additionalInformation),reference=clean(item.e2eReference??item.bankReference??item.customerReference),currency=(item.fundsCode||"EUR").toUpperCase();if(currency!=="EUR")throw new Error(`Nicht unterstützte Währung: ${currency}. Auswertungen sind derzeit ausschließlich in EUR möglich.`);const identity=["",booked,valued,item.amount.toFixed(2),currency,item.remoteAccountNumber,counterparty,purpose,reference].map(value=>String(value??"").trim().toLocaleLowerCase("de-DE")).join("|");return{accountReference:"",bookedOn:booked,valuedOn:valued,amount:item.amount,currency,direction:item.amount<0?"expense":"income",bookingType:clean(item.bookingText??item.transactionType),counterparty,counterpartyAccount:clean(item.remoteAccountNumber),purpose,bankReference:reference,fingerprint:hash(identity),originalData:{fints:JSON.stringify(item)}}})}
async function save(response:StatementResponse,context:{connection:Connection;settingsKey:string;localAccountId:string;memberId:string;householdId:string;userId:string}){
 const incoming=parsed(response),existingRows=await db.select().from(transactions).where(eq(transactions.accountId,context.localAccountId)),existing:ParsedTransaction[]=existingRows.map(row=>({accountReference:"",bookedOn:row.bookedOn,valuedOn:row.valuedOn??undefined,amount:Number(row.amount),currency:row.currency,direction:row.direction,bookingType:row.bookingType??undefined,counterparty:row.counterparty??undefined,purpose:row.purpose??undefined,bankReference:row.bankReference??undefined,fingerprint:row.fingerprint,originalData:{}})),duplicates=findDuplicates(incoming,existing),selected=duplicates.accepted;
 const[template]=await db.select({id:importTemplates.id}).from(importTemplates).where(and(eq(importTemplates.householdId,context.householdId),ilike(importTemplates.bankName,"%Sparkasse%"))).limit(1);if(!template)throw new Error("Keine Sparkassen-Importvorlage vorhanden.");
 const[record]=await db.insert(imports).values({accountId:context.localAccountId,templateId:template.id,uploadedBy:context.userId,fileFingerprint:hash(`fints:${Date.now()}:${randomUUID()}`),originalFilename:`Sparkasse FinTS ${new Date().toLocaleDateString("de-DE")}`,status:"completed",importedCount:selected.length,duplicateCount:duplicates.exact.length+duplicates.suspected.length,reviewCount:0,completedAt:new Date()}).returning();
 const inserted=selected.length?await db.insert(transactions).values(selected.map(item=>({accountId:context.localAccountId,importId:record.id,bookedOn:item.bookedOn,valuedOn:item.valuedOn,amount:item.amount.toFixed(2),currency:item.currency,direction:item.direction,bookingType:item.bookingType,counterparty:item.counterparty,counterpartyNormalized:normalizeMerchant(item.counterparty),purpose:item.purpose,bankReference:item.bankReference,fingerprint:item.fingerprint,originalDataEncrypted:encryptSecret(JSON.stringify(item.originalData))}))).onConflictDoNothing().returning({id:transactions.id}):[];
 if(inserted.length!==selected.length)await db.update(imports).set({importedCount:inserted.length,duplicateCount:duplicates.exact.length+duplicates.suspected.length+(selected.length-inserted.length)}).where(eq(imports.id,record.id));
 const local=await applyAutomaticAssignments({householdId:context.householdId,ownerMemberId:context.memberId,visibleAccountIds:[context.localAccountId]});
 if(response.bankingInformationUpdated)await db.update(systemSettings).set({valueEncrypted:encryptSecret(JSON.stringify(context.connection)),updatedAt:new Date()}).where(eq(systemSettings.key,context.settingsKey));
 await writeAudit("bank-import","Sparkassen-Umsätze wurden lesend über FinTS abgerufen.",{userId:context.userId,metadata:{accountId:context.localAccountId,imported:inserted.length,duplicates:duplicates.exact.length+duplicates.suspected.length+(selected.length-inserted.length)}});after(()=>runHouseholdIntegrityCheck(context.householdId,{audit:true,userId:context.userId}));return{ok:true,imported:inserted.length,duplicates:duplicates.exact.length+duplicates.suspected.length+(selected.length-inserted.length),locallyCategorized:local.applied};
}
export async function POST(request:Request){try{const user=await requireUser(),{member,accountIds}=await memberAndVisibleAccountIds(user.userId),body=schema.parse(await request.json()),settingsKey=`fints.sparkasse.${member.id}`;cleanupFinTsStatementSessions();
 if(body.action==="continue_tan"){const pending=finTsStatementSessions.get(body.token);if(!pending||pending.userId!==user.userId)throw new Error("Die TAN-Sitzung ist abgelaufen.");const response=await pending.client.getAccountStatementsWithTan(pending.tanReference,body.tan||undefined);if(!response.success)throw new Error(response.bankAnswers.map(a=>a.text).join(" · "));if(response.requiresTan){pending.tanReference=response.tanReference??pending.tanReference;return NextResponse.json({requiresTan:true,token:body.token,challenge:response.tanChallenge,isDecoupled:pending.client.config.selectedTanMethod?.isDecoupled??false})}(pending.connection as Connection).bankingInformation=pending.client.config.bankingInformation;finTsStatementSessions.delete(body.token);return NextResponse.json(await save(response,{connection:pending.connection as Connection,settingsKey:pending.settingsKey,localAccountId:pending.localAccountId,memberId:pending.memberId,householdId:pending.householdId,userId:pending.userId}))}
 const[stored]=await db.select().from(systemSettings).where(eq(systemSettings.key,settingsKey)).limit(1);if(!stored?.valueEncrypted)throw new Error("Sparkasse ist noch nicht eingerichtet.");const connection=JSON.parse(decryptSecret(stored.valueEncrypted)) as Connection;if(!accountIds.includes(String((stored.valueJson as {localAccountId?:string})?.localAccountId)))throw new Error("Das verbundene lokale Konto ist nicht mehr zugänglich.");const localAccountId=String((stored.valueJson as {localAccountId:string}).localAccountId),config=FinTSConfig.fromBankingInformation(connection.productId,finTsProductVersion(),connection.bankingInformation,connection.userId,connection.pin,connection.tanMethodId,connection.tanMediaName),client=new FinTSClient(config),to=new Date(),from=new Date(Date.now()-body.days*86400000),response=await client.getAccountStatements(connection.bankAccountNumber,from,to,true);if(!response.success)throw new Error(response.bankAnswers.map(a=>a.text).join(" · "));if(response.requiresTan){const token=randomUUID();finTsStatementSessions.set(token,{client,connection,settingsKey,tanReference:response.tanReference!,localAccountId,memberId:member.id,householdId:member.householdId,userId:user.userId,createdAt:Date.now()});return NextResponse.json({requiresTan:true,token,challenge:response.tanChallenge,isDecoupled:config.selectedTanMethod?.isDecoupled??false})}connection.bankingInformation=config.bankingInformation;return NextResponse.json(await save(response,{connection,settingsKey,localAccountId,memberId:member.id,householdId:member.householdId,userId:user.userId}));
 }catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Sparkassen-Umsätze konnten nicht abgerufen werden."},{status:400})}}
