"use client";
/* eslint-disable react-hooks/set-state-in-effect -- initiale Daten werden asynchron vom Server geladen */
import { useEffect,useState } from "react";
import { CalendarClock, CreditCard, RefreshCw, Repeat2, Trash2, TrendingDown, TrendingUp } from "lucide-react";
import { PageHeader } from "@/components/page-header";
type Item={merchant:string;accountId:string;averageAmount:number;cadenceDays:number;cadence:string;confidence:number;transactionIds:string[];priceChangePercent:number|null;lastSeenOn:string;categoryName:string;accountName:string;kind:"subscription"|"regular"};
const eur=new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"});
const annualCost=(item:Item)=>item.averageAmount*(item.cadenceDays<10?52:item.cadenceDays>300?1:12);

export default function RecurringPage(){
  const[items,setItems]=useState<Item[]>([]),[error,setError]=useState("");
  async function load(){const body=await fetch("/api/recurring").then(r=>r.json());if(Array.isArray(body))setItems(body);else setError(body.error)}
  async function remove(item:Item){if(!window.confirm(`„${item.merchant}“ nicht mehr als wiederkehrende Zahlung anzeigen? Die Umsätze selbst bleiben erhalten.`))return;const response=await fetch("/api/recurring",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify(item)});const body=await response.json();if(!response.ok){setError(body.error);return}setItems(current=>current.filter(candidate=>candidate!==item))}
  async function changeKind(item:Item){const kind=item.kind==="subscription"?"regular":"subscription";const response=await fetch("/api/recurring",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...item,kind})});const body=await response.json();if(!response.ok){setError(body.error);return}setItems(current=>current.map(candidate=>candidate===item?{...candidate,kind}:candidate))}
  useEffect(()=>{void load()},[]);
  const subscriptions=items.filter(item=>item.kind==="subscription"),regular=items.filter(item=>item.kind==="regular");
  const subscriptionAnnual=subscriptions.reduce((sum,item)=>sum+annualCost(item),0);
  const cards=(rows:Item[],empty:string)=>rows.length?<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map(item=><article key={`${item.merchant}-${item.accountName}`} className="card p-5"><div className="flex justify-between gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--surface-soft)] text-[var(--primary)]">{item.kind==="subscription"?<CreditCard size={20}/>:<CalendarClock size={20}/>}</span><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.confidence>=.9?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-800"}`}>{item.confidence>=.9?"Sehr sicher":"Wahrscheinlich"}</span><button type="button" onClick={()=>remove(item)} className="btn-secondary min-h-9 px-2.5 text-red-700" aria-label={`${item.merchant} aus wiederkehrenden Kosten entfernen`}><Trash2 size={16}/></button></div></div><h3 className="mt-4 font-bold">{item.merchant}</h3><p className="mt-1 text-sm muted">{item.categoryName} · {item.accountName}</p><div className="mt-4 text-2xl font-bold">{eur.format(item.averageAmount)}</div><p className="mt-1 text-sm muted">Ø {item.cadence.toLowerCase()} · {item.transactionIds.length} Buchungen</p>{item.kind==="subscription"&&<p className="mt-2 text-sm font-semibold text-[var(--primary)]">Etwa {eur.format(annualCost(item))} pro Jahr</p>}{item.priceChangePercent!==null&&Math.abs(item.priceChangePercent)>=3&&<div className={`mt-4 flex items-center gap-2 rounded-xl p-3 text-sm font-semibold ${item.priceChangePercent>0?"bg-red-50 text-red-800":"bg-emerald-50 text-emerald-800"}`}>{item.priceChangePercent>0?<TrendingUp size={17}/>:<TrendingDown size={17}/>}Letzte Zahlung {Math.abs(item.priceChangePercent).toLocaleString("de-DE",{maximumFractionDigits:1})} % {item.priceChangePercent>0?"höher":"niedriger"}</div>}<button type="button" onClick={()=>changeKind(item)} className="btn-secondary mt-4 w-full text-sm">{item.kind==="subscription"?"Zu regelmäßigen Zahlungen verschieben":"Als Abonnement einordnen"}</button></article>)}</section>:<div className="card p-5 text-sm muted">{empty}</div>;
  return <div className="space-y-7"><PageHeader eyebrow="Ausgabenprüfung" title="Wiederkehrende Kosten" description="Abonnements und andere regelmäßige Zahlungen werden getrennt dargestellt. Falsche Einordnungen kannst du jederzeit verschieben." action={<button onClick={load} className="btn-secondary"><RefreshCw size={17}/>Neu prüfen</button>}/>{error&&<div className="rounded-xl bg-red-50 p-4 text-red-800">{error}</div>}{items.length>0?<><section className="card flex flex-col justify-between gap-3 p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><CreditCard className="text-[var(--primary)]"/><div><div className="font-bold">Abonnement-Kosten</div><div className="text-sm muted">Aus Monats-, Wochen- und Jahreszahlungen hochgerechnet</div></div></div><div className="text-2xl font-bold">{eur.format(subscriptionAnnual)} <span className="text-sm font-normal muted">pro Jahr</span></div></section><section><div className="mb-4 flex items-center gap-3"><CreditCard className="text-[var(--primary)]"/><div><h2 className="text-xl font-bold">Abonnements</h2><p className="text-sm muted">Kündbare Dienste, Mitgliedschaften, Software sowie Telefon- und Internetverträge.</p></div></div>{cards(subscriptions,"Noch keine Abonnements erkannt.")}</section><section><div className="mb-4 flex items-center gap-3"><Repeat2 className="text-[var(--primary)]"/><div><h2 className="text-xl font-bold">Regelmäßige Zahlungen</h2><p className="text-sm muted">Zum Beispiel Miete, Kreditraten, Versicherungen oder Energieabschläge.</p></div></div>{cards(regular,"Noch keine anderen regelmäßigen Zahlungen erkannt.")}</section></>:!error&&<div className="card p-6 text-sm muted">Noch keine regelmäßige Zahlungsfolge mit mindestens drei Buchungen erkannt.</div>}</div>;
}
