"use client";
/* eslint-disable react-hooks/set-state-in-effect -- initiale Daten werden asynchron vom Server geladen */
import { useEffect,useState } from "react";
import Link from "next/link";
import { AlertTriangle, CheckCircle2, FileClock, PackageSearch, RefreshCw } from "lucide-react";
import { PageHeader } from "@/components/page-header";
type Account={id:string;name:string;transactionCount:number;from:string|null;to:string|null;lastImportAt:string|null;lastFilename:string|null;uncategorized:number;lowConfidence:number;missingMonths:string[]};type Quality={accounts:Account[];totals:{uncategorized:number;lowConfidence:number;amazonOpen:number}};
const date=(value:string|null)=>value?new Intl.DateTimeFormat("de-DE").format(new Date(`${value.slice(0,10)}T12:00:00`)):"–";
export default function DataQualityPage(){const[data,setData]=useState<Quality|null>(null);const[error,setError]=useState("");async function load(){const body=await fetch("/api/data-quality").then(r=>r.json());if(body.accounts)setData(body);else setError(body.error)}useEffect(()=>{void load()},[]);return <div className="space-y-7"><PageHeader eyebrow="Vollständigkeit" title="Datenqualität" description="Sieh auf einen Blick, wie aktuell und vollständig die Daten deiner sichtbaren Konten sind." action={<button onClick={load} className="btn-secondary"><RefreshCw size={17}/>Neu prüfen</button>}/>{error&&<div className="rounded-xl bg-red-50 p-4 text-red-800">{error}</div>}{data&&<><section className="grid gap-4 sm:grid-cols-3"><Link href="/umsaetze" className="card p-5 text-[var(--text)] no-underline"><AlertTriangle className="text-amber-600"/><div className="mt-3 text-3xl font-bold">{data.totals.uncategorized}</div><div className="text-sm muted">nicht zugeordnet</div></Link><Link href="/umsaetze" className="card p-5 text-[var(--text)] no-underline"><CheckCircle2 className="text-[var(--primary)]"/><div className="mt-3 text-3xl font-bold">{data.totals.lowConfidence}</div><div className="text-sm muted">Zuordnungen zu prüfen</div></Link><Link href="/einstellungen/amazon" className="card p-5 text-[var(--text)] no-underline"><PackageSearch className="text-[var(--primary)]"/><div className="mt-3 text-3xl font-bold">{data.totals.amazonOpen}</div><div className="text-sm muted">offene Amazon-Artikel</div></Link></section><section className="grid gap-4 lg:grid-cols-2">{data.accounts.map(account=><article key={account.id} className="card p-5"><div className="flex items-start justify-between"><div><h2 className="font-bold">{account.name}</h2><p className="mt-1 text-sm muted">{account.transactionCount} Umsätze · {date(account.from)} bis {date(account.to)}</p></div><FileClock className="text-[var(--primary)]"/></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div className="rounded-xl bg-[var(--surface-soft)] p-3"><dt className="muted">Letzter Import</dt><dd className="mt-1 font-semibold">{account.lastImportAt?new Intl.DateTimeFormat("de-DE",{dateStyle:"medium",timeStyle:"short"}).format(new Date(account.lastImportAt)):"Noch kein Import"}</dd></div><div className="rounded-xl bg-[var(--surface-soft)] p-3"><dt className="muted">Offene Zuordnungen</dt><dd className="mt-1 font-semibold">{account.uncategorized}</dd></div></dl>{account.missingMonths.length>0?<div className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><strong>Monate ohne Umsätze:</strong> {account.missingMonths.map(x=>new Intl.DateTimeFormat("de-DE",{month:"long",year:"numeric"}).format(new Date(`${x}-01T12:00:00Z`))).join(", ")}</div>:<div className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">Keine Lücke innerhalb des vorhandenen Zeitraums erkannt.</div>}</article>)}</section></>}</div>}
