"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react";
import { RefreshCw, Save, Trash2 } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { CategorySelectOptions, type SelectCategory } from "@/components/category-select-options";
type Rule={id:string;displayValue:string;ruleKind:string;accountName:string|null;categoryId:string;enabled:boolean;shared:boolean;conflict:boolean;matchedTransactions:number;editable:boolean};
export default function RulesPage(){
 const[rules,setRules]=useState<Rule[]>([]),[categories,setCategories]=useState<SelectCategory[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState("");
 async function load(){const[r,c]=await Promise.all([fetch("/api/categorization/rules").then(x=>x.json()),fetch("/api/categories").then(x=>x.json())]);if(Array.isArray(r))setRules(r);else setMessage(r.error);if(Array.isArray(c))setCategories(c)}
 useEffect(()=>{void load()},[]);
 async function save(rule:Rule,applyToExisting:boolean){setBusy(rule.id);setMessage("");const response=await fetch("/api/categorization/rules",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:rule.id,categoryId:rule.categoryId,enabled:rule.enabled,shared:rule.shared,applyToExisting})});const body=await response.json();setBusy("");if(!response.ok){setMessage(body.error);return}setMessage(applyToExisting?`Regel gespeichert und auf ${body.applied} vorhandene Umsätze angewendet.`:"Regel für zukünftige Zuordnungen gespeichert.");await load()}
 async function remove(rule:Rule){if(!confirm(`Regel „${rule.displayValue}“ wirklich löschen? Bereits zugeordnete Umsätze bleiben unverändert.`))return;setBusy(rule.id);const response=await fetch("/api/categorization/rules",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:rule.id})});const body=await response.json();setBusy("");if(!response.ok){setMessage(body.error);return}setMessage("Regel gelöscht. Vorhandene Umsätze wurden nicht verändert.");await load()}
 return <div className="space-y-7"><PageHeader eyebrow="Automatische Zuordnung" title="Gelernte Regeln" description="Korrigiere, pausiere oder lösche Händler- und Buchungstextregeln. Du entscheidest, ob bestehende Umsätze ebenfalls angepasst werden." action={<button onClick={load} className="btn-secondary"><RefreshCw size={17}/>Aktualisieren</button>}/>{message&&<div role="status" className="rounded-xl bg-[var(--surface-soft)] p-4 text-sm">{message}</div>}<section className="card overflow-hidden"><div className="divide-y divide-[var(--border)]">{rules.map(rule=><article key={rule.id} className="grid gap-4 p-5 lg:grid-cols-[1fr_260px_auto] lg:items-center"><div><h2 className="font-bold">{rule.displayValue}</h2><div className="mt-1 text-xs font-semibold text-[var(--primary)]">{rule.ruleKind}</div><p className="mt-1 text-sm muted">{rule.shared?"Alle freigegebenen Familienkonten":rule.accountName??"Bisherigem Konto nicht zugeordnet"} · {rule.matchedTransactions} passende {rule.matchedTransactions===1?"Buchung":"Buchungen"}{!rule.editable?" · geteilte Regel eines anderen Familienmitglieds":""}</p>{rule.conflict&&<p className="mt-2 rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-800">Regelkonflikt: Derselbe Auslöser besitzt unterschiedliche freigegebene Kategorien.</p>}<div className="mt-3 flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={rule.enabled} disabled={!rule.editable} onChange={e=>setRules(rows=>rows.map(x=>x.id===rule.id?{...x,enabled:e.target.checked}:x))}/> Aktiv</label><label className="flex items-center gap-2"><input type="checkbox" checked={rule.shared} disabled={!rule.editable} onChange={e=>setRules(rows=>rows.map(x=>x.id===rule.id?{...x,shared:e.target.checked}:x))}/> Familienkonten</label></div></div><select disabled={!rule.editable} value={rule.categoryId} onChange={e=>setRules(rows=>rows.map(x=>x.id===rule.id?{...x,categoryId:e.target.value}:x))} className="min-h-11 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3"><CategorySelectOptions categories={categories}/></select>{rule.editable&&<div className="flex flex-wrap gap-2 lg:justify-end"><button disabled={busy===rule.id} onClick={()=>save(rule,false)} className="btn-secondary"><Save size={16}/>Nur künftig</button><button disabled={busy===rule.id} onClick={()=>save(rule,true)} className="btn-primary"><RefreshCw size={16}/>Auch rückwirkend</button><button disabled={busy===rule.id} onClick={()=>remove(rule)} className="btn-secondary text-red-700" aria-label="Regel löschen"><Trash2 size={16}/></button></div>}</article>)}{!rules.length&&<p className="p-8 text-center muted">Noch keine gelernten Regeln vorhanden.</p>}</div></section></div>
}
