"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useState} from "react";
import {Eye,LoaderCircle,RefreshCw,Save,Trash2,X} from "lucide-react";
import {PageHeader} from "@/components/page-header";
import {CategorySelectOptions,type SelectCategory} from "@/components/category-select-options";

type Rule={id:string;displayValue:string;ruleKind:string;accountName:string|null;categoryId:string;enabled:boolean;shared:boolean;conflict:boolean;matchedTransactions:number;editable:boolean};
type ReferenceTransaction={id:string;bookedOn:string;amount:string;currency:string;counterparty:string|null;purpose:string|null;accountName:string;categoryName:string|null;categorizedBy:string|null};

export default function RulesPage(){
 const[rules,setRules]=useState<Rule[]>([]),[categories,setCategories]=useState<SelectCategory[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState("");
 const[referenceRule,setReferenceRule]=useState<Rule|null>(null),[references,setReferences]=useState<ReferenceTransaction[]>([]),[referenceTotal,setReferenceTotal]=useState(0),[referenceBusy,setReferenceBusy]=useState(false);
 async function load(){const[r,c]=await Promise.all([fetch("/api/categorization/rules").then(x=>x.json()),fetch("/api/categories").then(x=>x.json())]);if(Array.isArray(r))setRules(r);else setMessage(r.error);if(Array.isArray(c))setCategories(c)}
 useEffect(()=>{void load()},[]);
 async function openReferences(rule:Rule){setReferenceRule(rule);setReferences([]);setReferenceTotal(0);setReferenceBusy(true);const response=await fetch(`/api/categorization/rules?ruleId=${encodeURIComponent(rule.id)}`);const body=await response.json();setReferenceBusy(false);if(!response.ok){setMessage(body.error);setReferenceRule(null);return}setReferences(body.transactions);setReferenceTotal(body.total)}
 async function save(rule:Rule,applyToExisting:boolean){setBusy(rule.id);setMessage("");const response=await fetch("/api/categorization/rules",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:rule.id,categoryId:rule.categoryId,enabled:rule.enabled,shared:rule.shared,applyToExisting})});const body=await response.json();setBusy("");if(!response.ok){setMessage(body.error);return}setMessage(applyToExisting?`Regel gespeichert und auf ${body.applied} vorhandene Umsätze angewendet.`:"Regel für zukünftige Zuordnungen gespeichert.");await load()}
 async function remove(rule:Rule){if(!confirm(`Regel „${rule.displayValue}“ wirklich löschen? Bereits zugeordnete Umsätze bleiben unverändert.`))return;setBusy(rule.id);const response=await fetch("/api/categorization/rules",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:rule.id})});const body=await response.json();setBusy("");if(!response.ok){setMessage(body.error);return}setMessage("Regel gelöscht. Vorhandene Umsätze wurden nicht verändert.");await load()}
 return <div className="space-y-7">
  <PageHeader eyebrow="Automatische Zuordnung" title="Gelernte Regeln" description="Korrigiere, pausiere oder lösche Regeln. Öffne die passenden Buchungen, wenn dir der Auslöser allein nicht genug Kontext gibt." action={<button onClick={load} className="btn-secondary"><RefreshCw size={17}/>Aktualisieren</button>}/>
  {message&&<div role="status" className="rounded-xl bg-[var(--surface-soft)] p-4 text-sm">{message}</div>}
  <section className="card overflow-hidden"><div className="divide-y divide-[var(--border)]">{rules.map(rule=><article key={rule.id} className="grid gap-4 p-5 lg:grid-cols-[1fr_260px_auto] lg:items-center"><div><h2 className="break-words font-bold">{rule.displayValue}</h2><div className="mt-1 text-xs font-semibold text-[var(--primary)]">{rule.ruleKind}</div><div className="mt-1 flex flex-wrap items-center gap-x-2 text-sm muted"><span>{rule.shared?"Alle freigegebenen Familienkonten":rule.accountName??"Bisherigem Konto nicht zugeordnet"}</span><span aria-hidden="true">·</span><button type="button" onClick={()=>openReferences(rule)} className="inline-flex items-center gap-1 font-semibold text-[var(--primary)] underline decoration-dotted underline-offset-4"><Eye size={15}/>{rule.matchedTransactions} passende {rule.matchedTransactions===1?"Buchung":"Buchungen"} ansehen</button>{!rule.editable&&<span>· geteilte Regel eines anderen Familienmitglieds</span>}</div>{rule.conflict&&<p className="mt-2 rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-800">Regelkonflikt: Derselbe Auslöser besitzt unterschiedliche freigegebene Kategorien.</p>}<div className="mt-3 flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={rule.enabled} disabled={!rule.editable} onChange={e=>setRules(rows=>rows.map(x=>x.id===rule.id?{...x,enabled:e.target.checked}:x))}/> Aktiv</label><label className="flex items-center gap-2"><input type="checkbox" checked={rule.shared} disabled={!rule.editable} onChange={e=>setRules(rows=>rows.map(x=>x.id===rule.id?{...x,shared:e.target.checked}:x))}/> Familienkonten</label></div></div><select disabled={!rule.editable} value={rule.categoryId} onChange={e=>setRules(rows=>rows.map(x=>x.id===rule.id?{...x,categoryId:e.target.value}:x))} className="min-h-11 min-w-0 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3"><CategorySelectOptions categories={categories}/></select>{rule.editable&&<div className="flex flex-wrap gap-2 lg:justify-end"><button disabled={busy===rule.id} onClick={()=>save(rule,false)} className="btn-secondary"><Save size={16}/>Nur künftig</button><button disabled={busy===rule.id} onClick={()=>save(rule,true)} className="btn-primary"><RefreshCw size={16}/>Auch rückwirkend</button><button disabled={busy===rule.id} onClick={()=>remove(rule)} className="btn-secondary text-red-700" aria-label="Regel löschen"><Trash2 size={16}/></button></div>}</article>)}{!rules.length&&<p className="p-8 text-center muted">Noch keine gelernten Regeln vorhanden.</p>}</div></section>
  {referenceRule&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/45 p-0 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="reference-title" onMouseDown={event=>{if(event.currentTarget===event.target)setReferenceRule(null)}}><section className="max-h-[88dvh] w-full overflow-hidden rounded-t-2xl bg-[var(--surface)] shadow-2xl sm:max-w-3xl sm:rounded-2xl"><header className="flex items-start justify-between gap-4 border-b border-[var(--border)] p-5"><div className="min-w-0"><h2 id="reference-title" className="text-lg font-bold">Passende Buchungen</h2><p className="mt-1 break-words text-sm muted">Referenzen für „{referenceRule.displayValue}“</p></div><button type="button" onClick={()=>setReferenceRule(null)} className="btn-secondary shrink-0 p-3" aria-label="Schließen"><X size={18}/></button></header><div className="max-h-[68dvh] overflow-y-auto p-4 sm:p-5">{referenceBusy?<div className="flex items-center justify-center gap-2 py-12 muted"><LoaderCircle className="animate-spin"/>Buchungen werden geladen …</div>:<><p className="mb-4 text-sm muted">{referenceTotal} Treffer{referenceTotal>100?" · die neuesten 100 werden gezeigt":""}. So kannst du vor einer Regeländerung prüfen, worauf sie tatsächlich wirkt.</p><div className="space-y-3">{references.map(tx=><article key={tx.id} className="rounded-xl border border-[var(--border)] p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{new Intl.DateTimeFormat("de-DE").format(new Date(`${tx.bookedOn}T12:00:00`))} · {tx.counterparty??"Unbekannt"}</strong><strong className="whitespace-nowrap">{Number(tx.amount).toLocaleString("de-DE",{style:"currency",currency:tx.currency})}</strong></div><p className="mt-2 break-words text-sm leading-6 muted">{tx.purpose||"Kein Verwendungszweck"}</p><div className="mt-2 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-[var(--surface-soft)] px-2 py-1">{tx.accountName}</span><span className="rounded-full bg-[var(--surface-soft)] px-2 py-1">{tx.categoryName??"Nicht zugeordnet"}</span><span className="rounded-full bg-[var(--surface-soft)] px-2 py-1">{tx.categorizedBy??"Ohne Herkunft"}</span></div></article>)}{!references.length&&<p className="py-8 text-center muted">Für diese Regel wurden keine sichtbaren Buchungen gefunden.</p>}</div></>}</div></section></div>}
 </div>
}
