"use client";
import {useCallback,useEffect,useState} from "react";
import {Filter,Link2,LoaderCircle,RefreshCw,ShieldCheck,Sparkles} from "lucide-react";
import {CategorySelectOptions} from "@/components/category-select-options";
import {InlineCategoryCreate} from "@/components/inline-category-create";
import {confidenceBand as bandForConfidence,VERY_SAFE_CONFIDENCE}from"@/features/categorization/confidence";
type Category={id:string;name:string;isIncome:boolean;parentId:string|null};
type Item={id:string;productName:string;quantity:number;gross:number;categoryId:string|null;suggestion:{categoryId:string;categoryName:string;reason:string;confidence:number}|null};
type Group={key:string;orderDate:string;total:number;currency:string;matchedTransactionId:string|null;items:Item[];candidates:Array<{id:string;bookedOn:string;amount:number;currency:string;accountName:string;score:number;days:number;reason:string}>};
type Preview={count:number;batchSize:number;totalRounds?:number;provider?:string;model?:string;items:Array<{id:string}>;cost?:{lowEur:number;highEur:number}|null};
type AiSuggestion={id:string;categoryId:string;category:string;confidence:number;reason:string};
const date=(value:string)=>new Intl.DateTimeFormat("de-DE").format(new Date(`${value}T12:00:00`));
const money=(value:number,currency:string)=>value.toLocaleString("de-DE",{style:"currency",currency});

export function AmazonReconciliation(){
 const[groups,setGroups]=useState<Group[]>([]),[categories,setCategories]=useState<Category[]>([]),[transactions,setTransactions]=useState<Record<string,string>>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[matchFilter,setMatchFilter]=useState<"all"|"found"|"missing">("all"),[confidenceFilter,setConfidenceFilter]=useState<"all"|"very-safe"|"likely"|"check"|"none">("all"),[creatingForItem,setCreatingForItem]=useState<string|null>(null),[preview,setPreview]=useState<Preview|null>(null),[aiSuggestions,setAiSuggestions]=useState<Record<string,AiSuggestion>>({}),[analyzedIds,setAnalyzedIds]=useState<string[]>([]),[aiBusy,setAiBusy]=useState(false),[undoIds,setUndoIds]=useState<string[]>([]);
 const load=useCallback(async()=>{const[o,c]=await Promise.all([fetch("/api/amazon/orders").then(r=>r.json()),fetch("/api/categories").then(r=>r.json())]);if(Array.isArray(o)){setGroups(o);setTransactions(Object.fromEntries(o.map((g:Group)=>[g.key,g.matchedTransactionId??(g.candidates.length===1&&g.candidates[0].score>=.9?g.candidates[0].id:"")])))}else setMessage(o.error);if(Array.isArray(c))setCategories(c)},[]);
 const loadPreview=useCallback(async(excluded:string[]=[])=>{const q=excluded.length?`?exclude=${encodeURIComponent(excluded.join(","))}`:"";const r=await fetch(`/api/ai/categorize-amazon${q}`),b=await r.json();if(!r.ok){setMessage(b.error);return}setPreview(b)},[]);
 useEffect(()=>{void Promise.resolve().then(()=>Promise.all([load(),loadPreview()]))},[load,loadPreview]);
 async function setCategory(itemId:string,categoryId:string){if(categoryId==="__create__"){setCreatingForItem(itemId);return false}const r=await fetch("/api/amazon/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId,categoryId:categoryId||null})}),b=await r.json();if(!r.ok){setMessage(b.error);return false}setGroups(all=>all.map(g=>({...g,items:g.items.map(i=>i.id===itemId?{...i,categoryId:categoryId||null}:i)})));return true}
 async function acceptAi(id:string){const s=aiSuggestions[id];if(!s)return;if(await setCategory(id,s.categoryId))setAiSuggestions(all=>{const n={...all};delete n[id];return n})}
 async function analyze(){if(!preview?.items.length)return;setAiBusy(true);setMessage("");const ids=preview.items.map(i=>i.id),r=await fetch("/api/ai/categorize-amazon",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})}),b=await r.json();if(!r.ok){setMessage(b.error);setAiBusy(false);return}setAiSuggestions(all=>({...all,...Object.fromEntries(b.suggestions.map((s:AiSuggestion)=>[s.id,s]))}));const next=[...new Set([...analyzedIds,...ids])];setAnalyzedIds(next);setMessage(`${b.applied} sichere Artikel automatisch zugeordnet, ${b.suggestions.length} Vorschläge warten auf Bestätigung.${b.categoryProposals.length?` ${b.categoryProposals.length} Artikel benötigen eine neue Kategorie oder manuelle Zuordnung.`:""}${b.pricingAvailable?` Kosten: ${Number(b.estimatedCostEur).toLocaleString("de-DE",{minimumFractionDigits:4,maximumFractionDigits:6})} €.`:""}`);setAiBusy(false);await load();await loadPreview(next)}
 async function apply(g:Group){const transactionId=transactions[g.key];if(!transactionId){setMessage("Bitte eine passende Bankbuchung auswählen.");return}setBusy(true);const r=await fetch("/api/amazon/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemIds:g.items.map(i=>i.id),transactionId})}),b=await r.json();setBusy(false);if(!r.ok){setMessage(b.error);return}setMessage(`Amazon-Zahlung wurde auf ${b.splitCount} Kategorien verteilt.`);await load()}
 const suggestionFor=(item:Item)=>aiSuggestions[item.id]??(item.suggestion?{id:item.id,categoryId:item.suggestion.categoryId,category:item.suggestion.categoryName,confidence:item.suggestion.confidence,reason:item.suggestion.reason}:null);
 const confidenceBand=(item:Item)=>{const confidence=suggestionFor(item)?.confidence;return confidence===undefined?"none":bandForConfidence(confidence)};
 const unresolved=groups.filter(g=>!g.matchedTransactionId),foundCount=unresolved.filter(g=>g.candidates.length).length;
 const matchFiltered=unresolved.filter(g=>matchFilter==="all"||(matchFilter==="found"?g.candidates.length:!g.candidates.length));
 const visible=matchFiltered
  .filter(group=>confidenceFilter==="all"||group.items.some(item=>!item.categoryId&&confidenceBand(item)===confidenceFilter))
  .sort((a,b)=>{
   const highestA=Math.max(...a.items.map(item=>suggestionFor(item)?.confidence??-1));
   const highestB=Math.max(...b.items.map(item=>suggestionFor(item)?.confidence??-1));
   return highestB-highestA;
  });
 const visibleSuggestions=visible.flatMap(group=>group.items).filter(item=>!item.categoryId&&suggestionFor(item));
 const safeSuggestionCount=visibleSuggestions.filter(item=>(suggestionFor(item)?.confidence??0)>=VERY_SAFE_CONFIDENCE).length;
 async function acceptSuggested(mode:"safe"|"all"){const selected=visibleSuggestions.filter(item=>mode==="all"||(suggestionFor(item)?.confidence??0)>=VERY_SAFE_CONFIDENCE);if(!selected.length)return;setBusy(true);const acceptedIds:string[]=[];for(const item of selected){const suggestion=suggestionFor(item);if(suggestion&&await setCategory(item.id,suggestion.categoryId)){acceptedIds.push(item.id);setAiSuggestions(all=>{const next={...all};delete next[item.id];return next})}}setUndoIds(acceptedIds);setBusy(false);setMessage(`${acceptedIds.length} ${acceptedIds.length===1?"Amazon-Vorschlag wurde":"Amazon-Vorschläge wurden"} bestätigt.`)}
 async function undoSuggested(){if(!undoIds.length)return;setBusy(true);let restored=0;for(const id of undoIds)if(await setCategory(id,""))restored++;setUndoIds([]);setBusy(false);setMessage(`${restored} ${restored===1?"Amazon-Zuordnung wurde":"Amazon-Zuordnungen wurden"} rückgängig gemacht.`)}
 return <section className="space-y-4">
  {aiBusy&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-5" role="status"><div className="card max-w-md p-7 text-center"><LoaderCircle className="mx-auto animate-spin text-[var(--primary)]" size={38}/><h2 className="mt-4 text-xl font-bold">Amazon-Artikel werden analysiert</h2><p className="mt-2 text-sm muted">Bis zu 25 Artikel werden in dieser Runde eingeordnet. Bitte die Seite geöffnet lassen.</p></div></div>}
  {preview&&preview.count>0&&<article className="card flex flex-col justify-between gap-4 p-5 lg:flex-row lg:items-center"><div><div className="flex items-center gap-2"><Sparkles size={20}/><h2 className="font-bold">{preview.count} Amazon-Artikel ohne Kategorie</h2></div><p className="mt-1 text-sm muted">Nächste Runde: {preview.batchSize} Artikel · etwa {preview.totalRounds??Math.ceil(preview.count/25)} Runden{preview.provider&&preview.model?` · ${preview.provider} · ${preview.model}`:""}</p>{preview.cost&&<p className="mt-1 text-xs muted">Geschätzt: {preview.cost.lowEur.toLocaleString("de-DE",{minimumFractionDigits:4,maximumFractionDigits:6})}–{preview.cost.highEur.toLocaleString("de-DE",{minimumFractionDigits:4,maximumFractionDigits:6})} €</p>}</div><button disabled={aiBusy||!preview.batchSize} onClick={analyze} className="btn-primary"><Sparkles size={17}/>{analyzedIds.length?"Nächste KI-Runde":"Jetzt mit KI zuordnen"}</button></article>}
  <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-lg font-bold">Mit Bankumsätzen abstimmen</h2><p className="mt-1 text-sm muted">Artikel kategorisieren und anschließend mit einer betragsgleichen Amazon-Buchung verbinden.</p></div><div className="flex flex-wrap gap-2"><label className="flex min-h-11 items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 text-sm font-semibold"><Filter size={16}/><select value={matchFilter} onChange={e=>setMatchFilter(e.target.value as typeof matchFilter)} className="bg-transparent outline-none"><option value="all">Alle offenen ({unresolved.length})</option><option value="found">Bankbuchung gefunden ({foundCount})</option><option value="missing">Keine Bankbuchung ({unresolved.length-foundCount})</option></select></label><label className="flex min-h-11 items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 text-sm font-semibold"><ShieldCheck size={16}/><select value={confidenceFilter} onChange={e=>setConfidenceFilter(e.target.value as typeof confidenceFilter)} className="bg-transparent outline-none"><option value="all">Alle Sicherheitsstufen</option><option value="very-safe">Sehr sicher</option><option value="likely">Wahrscheinlich</option><option value="check">Bitte prüfen</option><option value="none">Ohne Vorschlag</option></select></label><button onClick={()=>void Promise.all([load(),loadPreview(analyzedIds)])} className="btn-secondary"><RefreshCw size={16}/>Aktualisieren</button></div></div>
  {message&&<div role="status" className="rounded-xl bg-[var(--surface-soft)] p-4 text-sm">{message}{undoIds.length>0&&<span className="mt-3 block"><button type="button" disabled={busy} onClick={undoSuggested} className="font-semibold text-[var(--primary)] underline">Letzte Sammelzuordnung rückgängig machen ({undoIds.length})</button></span>}</div>}
  {visibleSuggestions.length>0&&<article className="card p-4 sm:p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><h3 className="font-bold">Amazon-Vorschläge prüfen</h3><div className="mt-2 flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-emerald-100 px-3 py-1 font-semibold text-emerald-900">{safeSuggestionCount} sehr sicher</span><span className="rounded-full bg-amber-100 px-3 py-1 font-semibold text-amber-900">{visibleSuggestions.filter(item=>confidenceBand(item)==="likely").length} wahrscheinlich</span><span className="rounded-full bg-red-100 px-3 py-1 font-semibold text-red-900">{visibleSuggestions.filter(item=>confidenceBand(item)==="check").length} bitte prüfen</span></div></div><div className="flex flex-col gap-2 sm:flex-row"><button disabled={busy||safeSuggestionCount===0} onClick={()=>acceptSuggested("safe")} className="btn-secondary"><ShieldCheck size={17}/>Nur sehr sichere übernehmen ({safeSuggestionCount})</button><button disabled={busy||visibleSuggestions.length===0} onClick={()=>acceptSuggested("all")} className="btn-primary">Alle sichtbaren Vorschläge übernehmen ({visibleSuggestions.length})</button></div></div></article>}
  {!visible.length?<article className="card p-5 text-sm muted">{unresolved.length?"Für diesen Filter wurden keine Bestellungen gefunden.":"Keine offenen Amazon-Zuordnungen vorhanden."}</article>:visible.map(g=>{const selectedCandidate=g.candidates.find(candidate=>candidate.id===transactions[g.key]);return <article key={g.key} className="card p-5"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><h3 className="font-bold">Amazon-Bestellung vom {date(g.orderDate)}</h3><p className="mt-1 text-sm muted">{g.items.length} Artikel · {money(g.total,g.currency)}</p></div><select value={transactions[g.key]??""} onChange={e=>setTransactions(all=>({...all,[g.key]:e.target.value}))} className="min-h-11 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3"><option value="">Bankbuchung auswählen</option>{g.candidates.map(c=><option key={c.id} value={c.id}>{date(c.bookedOn)} · {c.accountName} · {money(Math.abs(c.amount),c.currency)} · {Math.round(c.score*100)} %</option>)}</select></div>{g.candidates.length>1&&!selectedCandidate&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><strong>{g.candidates.length} mögliche Bankbuchungen gefunden.</strong> Bitte den richtigen Treffer auswählen; die App entscheidet bei Mehrdeutigkeit nicht selbst.</p>}{selectedCandidate&&<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900"><strong>Bankbuchung {g.candidates.length===1?"eindeutig erkannt":"ausgewählt"}.</strong> {selectedCandidate.reason} · {Math.round(selectedCandidate.score*100)} % Übereinstimmung. Die Verknüpfung erfolgt erst über die Schaltfläche unten.</p>}
   <div className="mt-4 divide-y divide-[var(--border)] rounded-xl border border-[var(--border)]">{g.items.map(i=>{const suggestion=suggestionFor(i),band=confidenceBand(i);return <div key={i.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_230px] sm:items-center"><div><div className="font-semibold">{i.productName}</div><div className="mt-1 text-xs muted">Menge {i.quantity} · Artikelwert {money(i.gross,g.currency)}</div>{!i.categoryId&&suggestion&&<div className="mt-2 rounded-lg bg-[var(--surface-soft)] p-3 text-xs"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 font-semibold ${band==="very-safe"?"bg-emerald-100 text-emerald-900":band==="likely"?"bg-amber-100 text-amber-900":"bg-red-100 text-red-900"}`}>{band==="very-safe"?"Sehr sicher":band==="likely"?"Wahrscheinlich":"Bitte prüfen"}</span><strong>{suggestion.category}</strong><span className="muted">{Math.round(suggestion.confidence*100)} %</span></div><div className="mt-2 muted">{suggestion.reason}</div><button className="mt-2 font-bold text-[var(--primary)] underline" onClick={()=>suggestion===aiSuggestions[i.id]?acceptAi(i.id):setCategory(i.id,suggestion.categoryId)}>Diesen Vorschlag bestätigen</button></div>}</div><select value={i.categoryId??suggestion?.categoryId??""} onChange={e=>setCategory(i.id,e.target.value)} className="min-h-10 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3"><option value="">Kategorie auswählen</option><CategorySelectOptions categories={categories.filter(c=>!c.isIncome)}/><option value="__create__">＋ Neue Kategorie anlegen …</option></select></div>})}</div>
   <button disabled={busy||!transactions[g.key]||g.items.some(i=>!i.categoryId)} onClick={()=>apply(g)} className="btn-primary mt-4"><Link2 size={16}/>{busy?"Wird zugeordnet …":"Kategorien auf Bankbuchung anwenden"}</button>{!g.candidates.length&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><strong>Kategorie erkannt, Geldfluss noch nicht zugeordnet.</strong> Keine centgenau passende Amazon-Bankbuchung in derselben Währung und im Zeitraum von 21 Tagen gefunden. Nach dem nächsten Bankimport bitte erneut aktualisieren.</p>}</article>})}
  {creatingForItem&&<InlineCategoryCreate categories={categories} onClose={()=>setCreatingForItem(null)} onCreated={async category=>{setCategories(all=>[...all,category]);const id=creatingForItem;setCreatingForItem(null);await setCategory(id,category.id)}}/>}
 </section>
}
