"use client";
import {useCallback,useEffect,useState} from "react";
import {Filter,Link2,LoaderCircle,RefreshCw,ShieldCheck,Sparkles} from "lucide-react";
import {CategorySelectOptions} from "@/components/category-select-options";
import {InlineCategoryCreate} from "@/components/inline-category-create";
import {confidenceBand as bandForConfidence,VERY_SAFE_CONFIDENCE}from"@/features/categorization/confidence";
type Category={id:string;name:string;isIncome:boolean;parentId:string|null};
type Item={id:string;productName:string;quantity:number;gross:number;categoryId:string|null;suggestion:{categoryId:string;categoryName:string;reason:string;confidence:number}|null;proposal:{name:string;reason:string;confidence:number}|null};
type Group={key:string;orderDate:string;total:number;paymentGroupCount:number;currency:string;matchedTransactionId:string|null;items:Item[];candidates:Array<{id:string;bookedOn:string;amount:number;currency:string;accountName:string;score:number;days:number;reason:string}>};
type OrderCounts={importedItems:number;importedGroups:number;relevantGroups:number;excludedGroups:number;unlinkedGroups:number;openGroups:number;combinedGroups:number;combinedAssignments:number;linkedGroups:number;bankMatchFound:number;bankMatchMissing:number};
type OrdersResponse={groups:Group[];page:number;pageSize:number;pageCount:number;filteredCount:number;counts:OrderCounts};
type Preview={count:number;totalPending?:number;coverageItems?:number;excludedOutsideCoverage?:number;coverage?:{from:string;to:string;bankTransactions:number}|null;batchSize:number;totalRounds?:number;provider?:string;model?:string;items:Array<{id:string}>;cost?:{lowEur:number;highEur:number}|null};
type AiSuggestion={id:string;categoryId:string;category:string;confidence:number;reason:string};
type AiJob={id:string;status:"queued"|"running"|"paused"|"completed"|"failed";totalItems:number;processedItems:number;appliedItems:number;suggestionItems:number;proposalItems:number;rounds:number;estimatedCostEur:number;error:string|null};
const date=(value:string)=>new Intl.DateTimeFormat("de-DE").format(new Date(`${value}T12:00:00`));
const money=(value:number,currency:string)=>value.toLocaleString("de-DE",{style:"currency",currency});

export function AmazonReconciliation(){
 const[groups,setGroups]=useState<Group[]>([]),[categories,setCategories]=useState<Category[]>([]),[transactions,setTransactions]=useState<Record<string,string>>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[matchFilter,setMatchFilter]=useState<"all"|"found"|"missing">("all"),[confidenceFilter,setConfidenceFilter]=useState<"all"|"very-safe"|"likely"|"check"|"none">("all"),[creatingForItem,setCreatingForItem]=useState<string|null>(null),[preview,setPreview]=useState<Preview|null>(null),[aiSuggestions,setAiSuggestions]=useState<Record<string,AiSuggestion>>({}),[job,setJob]=useState<AiJob|null>(null),[showJob,setShowJob]=useState(false),[undoIds,setUndoIds]=useState<string[]>([]),[page,setPage]=useState(1),[pageCount,setPageCount]=useState(1),[filteredCount,setFilteredCount]=useState(0),[orderCounts,setOrderCounts]=useState<OrderCounts|null>(null);
 const load=useCallback(async()=>{const[o,c]=await Promise.all([fetch(`/api/amazon/orders?page=${page}&match=${matchFilter}`).then(r=>r.json()),fetch("/api/categories").then(r=>r.json())]);if(Array.isArray(o.groups)){const response=o as OrdersResponse;setGroups(response.groups);setPage(response.page);setPageCount(response.pageCount);setFilteredCount(response.filteredCount);setOrderCounts(response.counts);setTransactions(Object.fromEntries(response.groups.map((g:Group)=>[g.key,g.matchedTransactionId??(g.candidates.length===1&&g.candidates[0].score>=.9?g.candidates[0].id:"")])))}else setMessage(o.error);if(Array.isArray(c))setCategories(c)},[matchFilter,page]);
 const loadPreview=useCallback(async()=>{const r=await fetch("/api/ai/categorize-amazon"),b=await r.json();if(!r.ok){setMessage(b.error);return null}setPreview(b);return b as Preview},[]);
 useEffect(()=>{void Promise.resolve().then(()=>Promise.all([load(),loadPreview()]))},[load,loadPreview]);
 useEffect(()=>{let mounted=true;const poll=async()=>{const response=await fetch("/api/ai/jobs?kind=amazon"),body=await response.json();if(mounted&&response.ok)setJob(body)};void poll();const timer=setInterval(()=>void poll(),3000);return()=>{mounted=false;clearInterval(timer)}},[]);
 useEffect(()=>{if(job?.status==="completed")void Promise.resolve().then(()=>{setMessage(`Amazon-Analyse abgeschlossen: ${job.processedItems} Artikel in ${job.rounds} Runden · ${job.appliedItems} automatisch übernommen · ${job.suggestionItems} Vorschläge zur Prüfung.`);return Promise.all([load(),loadPreview()])});else if(job?.status==="failed")void Promise.resolve().then(()=>setMessage(`Amazon-Analyse angehalten: ${job.error??"Unbekannter Fehler"}`))},[job?.status,job?.processedItems,job?.rounds,job?.appliedItems,job?.suggestionItems,job?.error,load,loadPreview]);
 async function setCategory(itemId:string,categoryId:string){if(categoryId==="__create__"){setCreatingForItem(itemId);return false}const r=await fetch("/api/amazon/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId,categoryId:categoryId||null})}),b=await r.json();if(!r.ok){setMessage(b.error);return false}setGroups(all=>all.map(g=>({...g,items:g.items.map(i=>i.id===itemId?{...i,categoryId:categoryId||null}:i)})));return true}
 async function acceptAi(id:string){const s=aiSuggestions[id];if(!s)return;if(await setCategory(id,s.categoryId))setAiSuggestions(all=>{const n={...all};delete n[id];return n})}
 async function analyzeAll(){if(!preview?.items.length)return;setMessage("");const response=await fetch("/api/ai/jobs",{method:"POST"}),body=await response.json();if(!response.ok){setMessage(body.error);return}setJob(body);setShowJob(true)}
 async function changeJob(action:"pause"|"resume"){if(!job)return;const response=await fetch("/api/ai/jobs",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:job.id,action})}),body=await response.json();if(!response.ok){setMessage(body.error);return}setJob(body);setShowJob(action==="resume")}
 async function apply(g:Group){const transactionId=transactions[g.key];if(!transactionId){setMessage("Bitte eine passende Bankbuchung auswählen.");return}setBusy(true);const r=await fetch("/api/amazon/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemIds:g.items.map(i=>i.id),transactionId})}),b=await r.json();setBusy(false);if(!r.ok){setMessage(b.error);return}setMessage(`${b.paymentGroupCount>1?`${b.paymentGroupCount} Amazon-Zahlungsgruppen wurden gemeinsam`:`Amazon-Zahlung wurde`} auf ${b.splitCount} Kategorien verteilt.`);await load()}
 const suggestionFor=(item:Item)=>aiSuggestions[item.id]??(item.suggestion?{id:item.id,categoryId:item.suggestion.categoryId,category:item.suggestion.categoryName,confidence:item.suggestion.confidence,reason:item.suggestion.reason}:null);
 const confidenceBand=(item:Item)=>{const confidence=suggestionFor(item)?.confidence;return confidence===undefined?"none":bandForConfidence(confidence)};
 const unresolved=groups.filter(g=>!g.matchedTransactionId);
 const matchFiltered=unresolved.filter(g=>matchFilter==="all"||(matchFilter==="found"?g.candidates.length:!g.candidates.length));
 const visible=matchFiltered
  .filter(group=>confidenceFilter==="all"||group.items.some(item=>!item.categoryId&&confidenceBand(item)===confidenceFilter))
  .sort((a,b)=>{
   const highestA=Math.max(...a.items.map(item=>suggestionFor(item)?.confidence??-1));
   const highestB=Math.max(...b.items.map(item=>suggestionFor(item)?.confidence??-1));
   return highestB-highestA;
  });
 const visibleSuggestions=visible.flatMap(group=>group.items).filter(item=>!item.categoryId&&suggestionFor(item));
 const safeSuggestionCount=visibleSuggestions.filter(item=>(suggestionFor(item)?.confidence??0)>=VERY_SAFE_CONFIDENCE).length;
 async function acceptSuggested(mode:"safe"|"all"){const selected=visibleSuggestions.filter(item=>mode==="all"||(suggestionFor(item)?.confidence??0)>=VERY_SAFE_CONFIDENCE);if(!selected.length)return;setBusy(true);const acceptedIds:string[]=[];for(const item of selected){const suggestion=suggestionFor(item);if(suggestion&&await setCategory(item.id,suggestion.categoryId)){acceptedIds.push(item.id);setAiSuggestions(all=>{const next={...all};delete next[item.id];return next})}}setUndoIds(acceptedIds);setBusy(false);setMessage(`${acceptedIds.length} ${acceptedIds.length===1?"Amazon-Vorschlag wurde":"Amazon-Vorschläge wurden"} bestätigt.`)}
 async function undoSuggested(){if(!undoIds.length)return;setBusy(true);let restored=0;for(const id of undoIds)if(await setCategory(id,""))restored++;setUndoIds([]);setBusy(false);setMessage(`${restored} ${restored===1?"Amazon-Zuordnung wurde":"Amazon-Zuordnungen wurden"} rückgängig gemacht.`)}
 return <section className="space-y-4">
  {showJob&&job&&(job.status==="queued"||job.status==="running")&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-5" role="status"><div className="card w-full max-w-md p-7 text-center"><LoaderCircle className="mx-auto animate-spin text-[var(--primary)]" size={38}/><h2 className="mt-4 text-xl font-bold">Amazon-Artikel werden analysiert</h2><p className="mt-2 text-sm muted">Der Auftrag läuft serverseitig in sicheren 25er-Paketen weiter. Du kannst diese Ansicht oder den Browser schließen.</p><div className="mt-5 h-3 overflow-hidden rounded-full bg-[var(--surface-soft)]"><div className="h-full rounded-full bg-[var(--primary)] transition-all" style={{width:`${Math.min(100,job.totalItems?job.processedItems/job.totalItems*100:0)}%`}}/></div><p className="mt-3 font-bold">{job.processedItems} von {job.totalItems} Artikeln · {job.rounds} Runden</p><p className="mt-1 text-sm muted">{job.appliedItems} sehr sichere Zuordnungen bereits übernommen</p><div className="mt-5 flex flex-col gap-2 sm:flex-row"><button type="button" onClick={()=>setShowJob(false)} className="btn-secondary flex-1">Im Hintergrund weiterarbeiten</button><button type="button" onClick={()=>changeJob("pause")} className="btn-secondary flex-1">Nach dieser Runde pausieren</button></div></div></div>}
  {job&&(job.status==="running"||job.status==="queued"||job.status==="paused"||job.status==="failed")&&<article className="card flex flex-col justify-between gap-4 border-[var(--primary)] p-5 sm:flex-row sm:items-center"><div><h2 className="font-bold">KI-Auftrag: {job.status==="paused"?"pausiert":job.status==="failed"?"angehalten":"läuft im Hintergrund"}</h2><p className="mt-1 text-sm muted">{job.processedItems} von {job.totalItems} Artikeln · {job.rounds} Runden · Fortschritt bleibt bei Seitenwechsel und Neustart erhalten.</p>{job.error&&<p className="mt-1 text-sm text-red-700">{job.error}</p>}</div><div className="flex gap-2">{(job.status==="running"||job.status==="queued")&&<button type="button" className="btn-secondary" onClick={()=>setShowJob(true)}>Fortschritt anzeigen</button>}{(job.status==="paused"||job.status==="failed")&&<button type="button" className="btn-primary" onClick={()=>changeJob("resume")}>Fortsetzen</button>}</div></article>}
  {preview&&(preview.coverage||(preview.excludedOutsideCoverage??0)>0)&&<article className="card flex flex-col justify-between gap-4 p-5 lg:flex-row lg:items-center"><div><div className="flex items-center gap-2"><Sparkles size={20}/><h2 className="font-bold">Amazon-KI im Bankzeitraum</h2></div>{preview.coverage?<><p className="mt-1 text-sm muted">{preview.coverageItems??0} Artikel liegen im relevanten Zeitraum vom {date(preview.coverage.from)} bis {date(preview.coverage.to)}. Grundlage sind {preview.coverage.bankTransactions} Amazon-Bankbuchungen inklusive des 21-Tage-Abgleichfensters.</p><p className="mt-1 text-sm font-semibold">{preview.count>0?`${preview.count} davon warten noch auf die KI-Analyse.`:"Alle relevanten Artikel sind bereits kategorisiert oder analysiert."}</p></>:<p className="mt-1 text-sm text-amber-700">Es wurden noch keine Amazon-Bankbuchungen importiert. Deshalb startet keine kostenpflichtige KI-Analyse.</p>}{(preview.excludedOutsideCoverage??0)>0&&<p className="mt-1 text-sm muted">{preview.excludedOutsideCoverage} offene Artikel außerhalb dieses Zeitraums werden bewusst nicht analysiert und verursachen keine KI-Kosten.</p>}{preview.count>0&&<p className="mt-1 text-sm muted">Die Verarbeitung benötigt etwa {preview.totalRounds??Math.ceil(preview.count/25)} stabile 25er-Runden{preview.provider&&preview.model?` · ${preview.provider} · ${preview.model}`:""}.</p>}{preview.cost&&<p className="mt-1 text-xs muted">Gesamtkosten geschätzt: {(preview.cost.lowEur*(preview.totalRounds??1)).toLocaleString("de-DE",{minimumFractionDigits:4,maximumFractionDigits:4})}–{(preview.cost.highEur*(preview.totalRounds??1)).toLocaleString("de-DE",{minimumFractionDigits:4,maximumFractionDigits:4})} €</p>}</div>{preview.count>0&&<button disabled={Boolean(job&&["queued","running","paused"].includes(job.status))||!preview.batchSize} onClick={analyzeAll} className="btn-primary"><Sparkles size={17}/>Analyse als Hintergrundauftrag starten</button>}</article>}
  <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-lg font-bold">Amazon-Zahlungen im Bankzeitraum abstimmen</h2><p className="mt-1 text-sm muted">Hier werden Zahlungsgruppen statt einzelner Artikel gezählt. Mehrere Amazon-Gruppen können gemeinsam genau einer Bankbuchung entsprechen.</p>{orderCounts&&<p className="mt-2 text-xs muted">Im Bankzeitraum: {orderCounts.relevantGroups} Zahlungsgruppen · {orderCounts.linkedGroups} verbunden · {orderCounts.unlinkedGroups} unverbunden. Daraus entstehen {orderCounts.openGroups} offene Abstimmungen{orderCounts.combinedGroups>0?`; ${orderCounts.combinedGroups} Gruppen sind dabei in ${orderCounts.combinedAssignments} centgenauen Sammelabgleichen gebündelt`:""}. {orderCounts.excludedGroups} historische Gruppen sind ausgeblendet.</p>}</div><div className="flex flex-wrap gap-2"><label className="flex min-h-11 items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 text-sm font-semibold"><Filter size={16}/><select value={matchFilter} onChange={e=>{setMatchFilter(e.target.value as typeof matchFilter);setPage(1)}} className="bg-transparent outline-none"><option value="all">Offene Abstimmungen ({orderCounts?.openGroups??0})</option><option value="found">Bankbuchung gefunden ({orderCounts?.bankMatchFound??0})</option><option value="missing">Keine Bankbuchung ({orderCounts?.bankMatchMissing??0})</option></select></label><label className="flex min-h-11 items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 text-sm font-semibold"><ShieldCheck size={16}/><select value={confidenceFilter} onChange={e=>setConfidenceFilter(e.target.value as typeof confidenceFilter)} className="bg-transparent outline-none"><option value="all">Alle Sicherheitsstufen</option><option value="very-safe">Sehr sicher</option><option value="likely">Wahrscheinlich</option><option value="check">Bitte prüfen</option><option value="none">Ohne Vorschlag</option></select></label><button onClick={()=>void Promise.all([load(),loadPreview()])} className="btn-secondary"><RefreshCw size={16}/>Aktualisieren</button></div></div>
  {message&&<div role="status" className="rounded-xl bg-[var(--surface-soft)] p-4 text-sm">{message}{undoIds.length>0&&<span className="mt-3 block"><button type="button" disabled={busy} onClick={undoSuggested} className="font-semibold text-[var(--primary)] underline">Letzte Sammelzuordnung rückgängig machen ({undoIds.length})</button></span>}</div>}
  {visibleSuggestions.length>0&&<article className="card p-4 sm:p-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><h3 className="font-bold">Amazon-Vorschläge prüfen</h3><div className="mt-2 flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-emerald-100 px-3 py-1 font-semibold text-emerald-900">{safeSuggestionCount} sehr sicher</span><span className="rounded-full bg-amber-100 px-3 py-1 font-semibold text-amber-900">{visibleSuggestions.filter(item=>confidenceBand(item)==="likely").length} wahrscheinlich</span><span className="rounded-full bg-red-100 px-3 py-1 font-semibold text-red-900">{visibleSuggestions.filter(item=>confidenceBand(item)==="check").length} bitte prüfen</span></div></div><div className="flex flex-col gap-2 sm:flex-row"><button disabled={busy||safeSuggestionCount===0} onClick={()=>acceptSuggested("safe")} className="btn-secondary"><ShieldCheck size={17}/>Nur sehr sichere übernehmen ({safeSuggestionCount})</button><button disabled={busy||visibleSuggestions.length===0} onClick={()=>acceptSuggested("all")} className="btn-primary">Alle sichtbaren Vorschläge übernehmen ({visibleSuggestions.length})</button></div></div></article>}
  {!visible.length?<article className="card p-5 text-sm muted">{filteredCount?"Auf dieser Seite passt keine Bestellung zum Sicherheitsfilter.":"Keine offenen Amazon-Zahlungen für diesen Filter vorhanden."}</article>:visible.map(g=>{const selectedCandidate=g.candidates.find(candidate=>candidate.id===transactions[g.key]);return <article key={g.key} className="card p-5"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><h3 className="font-bold">{g.paymentGroupCount>1?`${g.paymentGroupCount} Amazon-Zahlungsgruppen gemeinsam`:`Amazon-Zahlungsgruppe vom ${date(g.orderDate)}`}</h3><p className="mt-1 text-sm muted">{g.items.length} Artikel · zusammen {money(g.total,g.currency)}</p></div><select value={transactions[g.key]??""} onChange={e=>setTransactions(all=>({...all,[g.key]:e.target.value}))} className="min-h-11 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3"><option value="">Bankbuchung auswählen</option>{g.candidates.map(c=><option key={c.id} value={c.id}>{date(c.bookedOn)} · {c.accountName} · {money(Math.abs(c.amount),c.currency)} · {Math.round(c.score*100)} %</option>)}</select></div>{g.candidates.length>1&&!selectedCandidate&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><strong>{g.candidates.length} mögliche Bankbuchungen gefunden.</strong> Bitte den richtigen Treffer auswählen; die App entscheidet bei Mehrdeutigkeit nicht selbst.</p>}{selectedCandidate&&<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900"><strong>Bankbuchung {g.candidates.length===1?"eindeutig erkannt":"ausgewählt"}.</strong> {selectedCandidate.reason} · {Math.round(selectedCandidate.score*100)} % Übereinstimmung. Die Verknüpfung erfolgt erst über die Schaltfläche unten.</p>}
   <div className="mt-4 divide-y divide-[var(--border)] rounded-xl border border-[var(--border)]">{g.items.map(i=>{const suggestion=suggestionFor(i),band=confidenceBand(i);return <div key={i.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_230px] sm:items-center"><div><div className="font-semibold">{i.productName}</div><div className="mt-1 text-xs muted">Menge {i.quantity} · Artikelwert {money(i.gross,g.currency)}</div>{!i.categoryId&&suggestion&&<div className="mt-2 rounded-lg bg-[var(--surface-soft)] p-3 text-xs"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 font-semibold ${band==="very-safe"?"bg-emerald-100 text-emerald-900":band==="likely"?"bg-amber-100 text-amber-900":"bg-red-100 text-red-900"}`}>{band==="very-safe"?"Sehr sicher":band==="likely"?"Wahrscheinlich":"Bitte prüfen"}</span><strong>{suggestion.category}</strong><span className="muted">{Math.round(suggestion.confidence*100)} %</span></div><div className="mt-2 muted">{suggestion.reason}</div><button className="mt-2 font-bold text-[var(--primary)] underline" onClick={()=>suggestion===aiSuggestions[i.id]?acceptAi(i.id):setCategory(i.id,suggestion.categoryId)}>Diesen Vorschlag bestätigen</button></div>}{!i.categoryId&&!suggestion&&i.proposal&&<div className="mt-2 rounded-lg bg-amber-50 p-3 text-xs text-amber-950"><strong>Neue Kategorie vorgeschlagen: {i.proposal.name}</strong><p className="mt-1">{i.proposal.reason} · {Math.round(i.proposal.confidence*100)} %</p><button type="button" className="mt-2 font-bold underline" onClick={()=>setCreatingForItem(i.id)}>Kategorie prüfen und anlegen</button></div>}</div><select value={i.categoryId??suggestion?.categoryId??""} onChange={e=>setCategory(i.id,e.target.value)} className="min-h-10 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3"><option value="">Kategorie auswählen</option><CategorySelectOptions categories={categories.filter(c=>!c.isIncome)}/><option value="__create__">＋ Neue Kategorie anlegen …</option></select></div>})}</div>
   <button disabled={busy||!transactions[g.key]||g.items.some(i=>!i.categoryId)} onClick={()=>apply(g)} className="btn-primary mt-4"><Link2 size={16}/>{busy?"Wird zugeordnet …":"Kategorien auf Bankbuchung anwenden"}</button>{!g.candidates.length&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><strong>Kategorie erkannt, Geldfluss noch nicht zugeordnet.</strong> Keine centgenau passende Amazon-Bankbuchung in derselben Währung und im Zeitraum von 21 Tagen gefunden. Nach dem nächsten Bankimport bitte erneut aktualisieren.</p>}</article>})}
  {pageCount>1&&<nav className="card flex items-center justify-between gap-3 p-4" aria-label="Offene Amazon-Zahlungen durchblättern"><button type="button" className="btn-secondary" disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Zurück</button><span className="text-center text-sm muted">Seite {page} von {pageCount} · {filteredCount} offene Zahlungen</span><button type="button" className="btn-secondary" disabled={page>=pageCount} onClick={()=>setPage(value=>value+1)}>Weiter</button></nav>}
  {creatingForItem&&<InlineCategoryCreate categories={categories} onClose={()=>setCreatingForItem(null)} onCreated={async category=>{setCategories(all=>[...all,category]);const id=creatingForItem;setCreatingForItem(null);await setCategory(id,category.id)}}/>}
 </section>
}
