"use client";
import { FormEvent, useState } from "react";
import { Plus, X } from "lucide-react";
import { flattenCategoryHierarchy } from "@/features/categories/hierarchy";
import type { SelectCategory } from "@/components/category-select-options";

export function InlineCategoryCreate({categories,defaultIsIncome=false,onCreated,onClose}:{categories:SelectCategory[];defaultIsIncome?:boolean;onCreated:(category:SelectCategory)=>void|Promise<void>;onClose:()=>void}){
  const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  const[isIncome,setIsIncome]=useState(defaultIsIncome);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError("");const response=await fetch("/api/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),color:form.get("color"),icon:"Tag",isIncome:form.get("isIncome")==="on",parentId:form.get("parentId")||null})});const body=await response.json();setBusy(false);if(!response.ok){setError(body.error??"Kategorie konnte nicht angelegt werden.");return}await onCreated(body)}
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/35 p-3 sm:items-center" role="dialog" aria-modal="true" aria-labelledby="inline-category-title"><form onSubmit={submit} className="card w-full max-w-lg p-6"><div className="flex items-start justify-between gap-4"><div><h2 id="inline-category-title" className="text-xl font-bold">Kategorie direkt anlegen</h2><p className="mt-1 text-sm muted">Du bleibst bei deiner aktuellen Zuordnung. Die neue Kategorie wird anschließend sofort übernommen.</p></div><button type="button" onClick={onClose} className="btn-secondary min-h-10 px-3" aria-label="Dialog schließen"><X size={18}/></button></div>{error&&<div role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</div>}<div className="mt-5 grid gap-4 sm:grid-cols-[1fr_90px]"><label className="text-sm font-semibold">Name<input name="name" required minLength={2} maxLength={60} autoFocus className="mt-2 min-h-11 w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-3" placeholder="z. B. Tierbedarf"/></label><label className="text-sm font-semibold">Farbe<input name="color" type="color" defaultValue="#136f78" className="mt-2 h-11 w-full rounded-xl border border-[var(--border)] bg-[var(--background)] p-1"/></label></div><label className="mt-4 block text-sm font-semibold">Unterkategorie von<select name="parentId" className="mt-2 min-h-11 w-full rounded-xl border border-[var(--border)] bg-[var(--background)] px-3"><option value="">Keine – Hauptkategorie</option>{flattenCategoryHierarchy(categories.filter(category=>category.isIncome===isIncome)).map(({category,depth})=><option key={category.id} value={category.id}>{"— ".repeat(depth)}{category.name}</option>)}</select></label><label className="mt-4 flex items-center gap-3 rounded-xl bg-[var(--surface-soft)] p-4 text-sm font-semibold"><input name="isIncome" type="checkbox" checked={isIncome} onChange={event=>setIsIncome(event.target.checked)} className="h-5 w-5 accent-[var(--primary)]"/>Einnahmekategorie</label><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={onClose} className="btn-secondary">Abbrechen</button><button disabled={busy} className="btn-primary"><Plus size={17}/>{busy?"Wird angelegt …":"Anlegen & übernehmen"}</button></div></form></div>
}
