"use client";
import{useEffect,useState}from"react";
import Link from"next/link";
import{BarChart3,Check,ChevronRight,FileUp,PackageSearch,ShieldCheck,Sparkles}from"lucide-react";
type Status={accountCount:number;transactionCount:number;uncategorizedCount:number;reviewCount:number;deferredCount:number;amazonOpenCount:number;unresolvedSources:{amazon:number;paypal:number;card:number};lastImportAt:string|null;aiConfigured:boolean;bankConnected:boolean};
export function MonthlyWorkflow(){const[status,setStatus]=useState<Status|null>(null);useEffect(()=>{fetch("/api/workflow/status").then(r=>r.json()).then(body=>{if(typeof body.accountCount==="number")setStatus(body)})},[]);if(!status)return null;const sourceTotal=Object.values(status.unresolvedSources??{}).reduce((a,b)=>a+b,0);const clarified=status.transactionCount>0&&status.uncategorizedCount===0&&status.reviewCount===0&&status.deferredCount===0&&status.amazonOpenCount===0;const steps=[
 {title:status.bankConnected?"Bankumsätze abrufen":"Kontoauszug importieren",detail:status.lastImportAt?`Letzter Abruf/Import: ${new Intl.DateTimeFormat("de-DE",{dateStyle:"medium"}).format(new Date(status.lastImportAt))}`:status.accountCount?(status.bankConnected?"Bereit für den ersten Bankabruf":"Bereit für den ersten Kontoauszug"):"Zuerst ein Konto anlegen",href:status.accountCount?(status.bankConnected?"/einstellungen/sparkasse":"/einstellungen/import"):"/konten",done:status.transactionCount>0,icon:FileUp},
 {title:"Sichere Regeln anwenden",detail:status.transactionCount?"Geschieht nach jedem Import automatisch":"Nach dem Import verfügbar",href:"/umsaetze",done:status.transactionCount>0,icon:ShieldCheck},
 {title:"KI-Restmenge bearbeiten",detail:status.uncategorizedCount?`${status.uncategorizedCount} offen · in 25er-Runden${status.aiConfigured?"":" · KI fehlt"}`:"Keine offene Restmenge",href:"/umsaetze",done:status.transactionCount>0&&status.uncategorizedCount===0,icon:Sparkles},
 {title:"Vorschläge prüfen",detail:status.reviewCount||status.deferredCount?`${status.reviewCount} zu prüfen · ${status.deferredCount} später` : status.transactionCount?"Keine Prüfung offen":"Nach der KI-Analyse verfügbar",href:"/umsaetze?confidence=review",done:status.transactionCount>0&&status.reviewCount===0&&status.deferredCount===0,icon:Check},
 {title:"Sammelzahlungen ergänzen",detail:sourceTotal?`${status.unresolvedSources.amazon} Amazon · ${status.unresolvedSources.paypal} PayPal · ${status.unresolvedSources.card} Karte`:status.amazonOpenCount?`${status.amazonOpenCount} Amazon-Artikel noch abzustimmen`:"Keine Zusatzdatei erforderlich",href:status.unresolvedSources.amazon||status.amazonOpenCount?"/einstellungen/amazon":"/einstellungen/import",done:sourceTotal===0&&status.amazonOpenCount===0,icon:PackageSearch},
 {title:"Analyse ansehen",detail:clarified?"Deine geprüfte Monatsanalyse ist bereit":status.transactionCount?"Bereits sichtbar, nach Abschluss vollständig":"Nach dem ersten Import verfügbar",href:"#analyse",done:clarified,icon:BarChart3}];
 const nextIndex=clarified?steps.length-1:Math.max(0,steps.findIndex(step=>!step.done));const next=steps[nextIndex];const NextIcon=next.icon;const completed=steps.filter(step=>step.done).length;
 return <section className="card p-5 sm:p-6"><div><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--primary)]">Dein nächster Schritt</p><h2 className="mt-1 text-xl font-bold">{next.title}</h2></div><span className="rounded-full bg-[var(--surface-soft)] px-3 py-1 text-xs font-semibold">{completed}/{steps.length} erledigt</span></div><p className="mt-2 text-sm leading-6 muted">{next.detail}</p><Link href={next.href} className="btn-primary mt-4 w-full sm:w-auto"><NextIcon size={17}/>{next.title}<ChevronRight size={17}/></Link></div><details className="mt-5 border-t border-[var(--border)] pt-4"><summary className="cursor-pointer text-sm font-semibold text-[var(--primary)]">Gesamten Monatsablauf anzeigen</summary><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{steps.map(({title,detail,href,done,icon:Icon},index)=><Link key={title} href={href} className={`flex items-start gap-3 rounded-xl border p-4 text-[var(--text)] no-underline hover:bg-[var(--surface-soft)] ${index===nextIndex?"border-[var(--primary)]":"border-[var(--border)]"}`}><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${done?"bg-emerald-100 text-emerald-800":"bg-[var(--surface-soft)] text-[var(--primary)]"}`}>{done?<Check size={17}/>:index+1}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-2 font-bold"><Icon size={16}/>{title}</span><span className="mt-1 block text-sm muted">{detail}</span></span><ChevronRight size={18} className="mt-2 shrink-0 muted"/></Link>)}</div></details></section>}
