import {ArrowDown,BarChart3,BrainCircuit,CheckCircle2,FileUp,PackageSearch,RefreshCw,ShieldCheck} from "lucide-react";
import {PageHeader} from "@/components/page-header";

const steps=[
 {icon:FileUp,title:"1. Bankkonto importieren",text:"Der Kontoauszug ist die finanzielle Grundlage. Dubletten, vorgemerkte und 0-Euro-Buchungen werden bereinigt."},
 {icon:ShieldCheck,title:"2. Sichere Zuordnung",text:"Ausdrücklich gespeicherte Regeln, eindeutige Begriffe und bekannte Abos werden lokal und ohne KI-Kosten angewendet. Manuelle Einzelentscheidungen werden dabei nie überschrieben und nie ungefragt als Regel gelernt."},
 {icon:BrainCircuit,title:"3. KI-Restmenge",text:"Nur noch ungeklärte Buchungen gehen in 25er-Runden an die konfigurierte KI. Deine Vertrauensgrenze bestimmt, was bestätigt werden muss."},
 {icon:CheckCircle2,title:"4. Vorschläge prüfen",text:"Unsichere Treffer und neue Kategorien brauchen eine Entscheidung. Neue Kategorien entstehen niemals ohne ausdrückliche Bestätigung."},
 {icon:PackageSearch,title:"5. Sammelzahlungen auflösen",text:"Amazon-, PayPal- oder Kartenbuchungen können mehrere Artikel und Kategorien enthalten. Der Zusatzexport zerlegt die Sammelbuchung fachlich korrekt."},
 {icon:RefreshCw,title:"6. Mit Bankbuchung abstimmen",text:"Artikelkategorien werden centgenau auf die gefundene Bankbuchung übertragen. Mehrere Kategorien erzeugen eine Aufteilung statt einer pauschalen Zuordnung."},
 {icon:BarChart3,title:"7. Analyse",text:"Erst wenn offene Zuordnungen und Sammelzahlungen geklärt sind, gilt die Analyse als vollständig. Zwischenergebnisse bleiben trotzdem sichtbar."},
] as const;

export default function HelpPage(){return <div className="space-y-7"><PageHeader eyebrow="Admin · Hilfe" title="So verarbeitet der Finanzplaner deine Daten" description="Der Kontoauszug bleibt die Quelle für den tatsächlichen Geldfluss. Zusatzexporte erklären, wofür Sammelzahlungen verwendet wurden."/><section className="card p-5 sm:p-7"><div className="mx-auto max-w-3xl">{steps.map(({icon:Icon,title,text},index)=><div key={title}><article className="grid gap-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5 sm:grid-cols-[48px_1fr] sm:items-center"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[var(--surface-soft)] text-[var(--primary)]"><Icon size={24}/></span><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm leading-6 muted">{text}</p></div></article>{index<steps.length-1&&<div className="flex h-10 items-center justify-center text-[var(--primary)]"><ArrowDown size={22}/></div>}</div>)}</div></section><section className="grid gap-4 lg:grid-cols-2"><article className="card p-5"><h2 className="font-bold">Warum Amazon trotz „0 offen“ wichtig sein kann</h2><p className="mt-2 text-sm leading-6 muted">Eine Amazon-Abbuchung ist nur eine Sammelzahlung. „0 nicht zugeordnet“ bei Bankumsätzen sagt deshalb nicht, dass alle enthaltenen Artikel erklärt sind. Als offene Aufgabe zählen nur unverknüpfte Amazon-Zahlungsgruppen im Zeitraum der tatsächlich vorhandenen Amazon-Bankbuchungen – historische Bestellungen außerhalb dieses Zeitraums nicht.</p></article><article className="card p-5"><h2 className="font-bold">Regel für neue Kategorien</h2><p className="mt-2 text-sm leading-6 muted">Die KI darf ausschließlich Vorschläge machen. Anlegen muss der Benutzer jede neue Kategorie ausdrücklich selbst. Doppelte Namen und Sammelbegriffe wie „Sonstiges“, „Einkäufe“ oder „Shopping“ blockiert die Anwendung zentral.</p></article></section></div>}
