"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import Link from "next/link";
import { useEffect, useState } from "react";
import { BookOpenCheck, Eye, PackageSearch, RefreshCw, Save, ShieldCheck, Trash2, X } from "lucide-react";
import { ASSIGNMENT_PIPELINE } from "@/features/categorization/assignment-policy";
import { CategorySelectOptions, type SelectCategory } from "@/components/category-select-options";
import { PageHeader } from "@/components/page-header";

type BankRule={id:string;displayValue:string;ruleKind:string;accountName:string|null;categoryId:string;enabled:boolean;shared:boolean;conflict:boolean;matchedTransactions:number;editable:boolean};
type AmazonRule={id:string;pattern:string;categoryId:string;enabled:boolean};
type Reference={id:string;bookedOn:string;amount:string;currency:string;counterparty:string|null;purpose:string|null;accountName:string;categoryName:string|null;categorizedBy:string|null};

export default function AutomationPage(){
 const[bankRules,setBankRules]=useState<BankRule[]>([]);const[amazonRules,setAmazonRules]=useState<AmazonRule[]>([]);const[categories,setCategories]=useState<SelectCategory[]>([]);const[message,setMessage]=useState("");const[busy,setBusy]=useState("");
 const[referenceRule,setReferenceRule]=useState<BankRule|null>(null);const[references,setReferences]=useState<Reference[]>([]);const[referenceTotal,setReferenceTotal]=useState(0);const[referenceBusy,setReferenceBusy]=useState(false);
 async function load(){const[bank,amazon,cats]=await Promise.all([fetch("/api/categorization/rules").then(r=>r.json()),fetch("/api/amazon/rules?view=rules").then(r=>r.json()),fetch("/api/categories").then(r=>r.json())]);if(Array.isArray(bank))setBankRules(bank);else setMessage(bank.error);if(Array.isArray(amazon.rules))setAmazonRules(amazon.rules);else if(amazon.error)setMessage(amazon.error);if(Array.isArray(cats))setCategories(cats)}
 useEffect(()=>{void load()},[]);
 async function saveBank(rule:BankRule,applyToExisting:boolean){setBusy(rule.id);setMessage("");const response=await fetch("/api/categorization/rules",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:rule.id,categoryId:rule.categoryId,enabled:rule.enabled,shared:rule.shared,applyToExisting})});const body=await response.json();setBusy("");if(!response.ok){setMessage(body.error);return}setMessage(applyToExisting?`Regel gespeichert und auf ${body.applied} vorhandene Umsätze angewendet.`:"Regel für künftige Umsätze gespeichert.");await load()}
 async function saveAmazon(rule:AmazonRule,categoryId:string){setBusy(rule.id);const response=await fetch("/api/amazon/rules",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pattern:rule.pattern,categoryId})});const body=await response.json();setBusy("");if(!response.ok){setMessage(body.error);return}setMessage(`Amazon-Regel gespeichert und auf ${body.matched} vorhandene Artikel angewendet.`);await load()}
 async function remove(kind:"bank"|"amazon",id:string,label:string){if(!confirm(`Regel „${label}“ löschen? Bereits zugeordnete Buchungen oder Artikel bleiben unverändert.`))return;setBusy(id);const response=await fetch(kind==="bank"?"/api/categorization/rules":"/api/amazon/rules",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const body=await response.json();setBusy("");if(!response.ok){setMessage(body.error);return}setMessage("Regel gelöscht. Vorhandene Zuordnungen bleiben erhalten.");await load()}
 async function openReferences(rule:BankRule){setReferenceRule(rule);setReferences([]);setReferenceTotal(0);setReferenceBusy(true);const response=await fetch(`/api/categorization/rules?ruleId=${encodeURIComponent(rule.id)}`);const body=await response.json();setReferenceBusy(false);if(!response.ok){setMessage(body.error);setReferenceRule(null);return}setReferences(body.transactions);setReferenceTotal(body.total)}
 const expenseCategories=categories.filter(category=>!category.isIncome);
 return <div className="space-y-7">
  <PageHeader eyebrow="Eine gemeinsame Logik" title="Zuordnungen & Automatik" description="Hier verwaltest du das gesamte gespeicherte Zuordnungswissen. Unklare Fälle bleiben offen; manuelle Entscheidungen haben immer Vorrang." action={<button type="button" onClick={load} className="btn-secondary"><RefreshCw size={17}/>Aktualisieren</button>}/>
  {message&&<div role="status" className="rounded-xl bg-[var(--surface-soft)] p-4 text-sm">{message}</div>}
  <section className="card p-5 sm:p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><ShieldCheck className="text-[var(--primary)]"/>Feste Reihenfolge</h2><p className="mt-2 text-sm muted">Eine spätere Stufe darf eine Entscheidung aus einer höheren Stufe nicht überschreiben.</p><ol className="mt-5 grid gap-3 lg:grid-cols-5">{ASSIGNMENT_PIPELINE.map(step=><li key={step.priority} className="rounded-xl border border-[var(--border)] p-4"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[var(--surface-soft)] text-sm font-bold text-[var(--primary)]">{step.priority}</span><strong className="mt-3 block text-sm">{step.title}</strong><span className="mt-1 block text-xs leading-5 muted">{step.detail}</span></li>)}</ol></section>
  <section className="card overflow-hidden"><header className="flex flex-col justify-between gap-3 border-b border-[var(--border)] p-5 sm:flex-row sm:items-center"><div><h2 className="font-bold">Bank- und Buchungstextregeln</h2><p className="mt-1 text-sm muted">{bankRules.length} bestätigte Regeln · gelten je Konto oder für freigegebene Familienkonten</p></div></header><div className="divide-y divide-[var(--border)]">{bankRules.map(rule=><article key={rule.id} className="grid gap-4 p-5 lg:grid-cols-[1fr_250px_auto] lg:items-center"><div><strong className="break-words">{rule.displayValue}</strong><div className="mt-1 text-xs font-semibold text-[var(--primary)]">{rule.ruleKind}</div><div className="mt-1 text-sm muted">{rule.shared?"Freigegebene Familienkonten":rule.accountName??"Keinem Konto zugeordnet"} · <button type="button" onClick={()=>void openReferences(rule)} className="font-semibold text-[var(--primary)] underline decoration-dotted"><Eye size={14} className="inline"/> {rule.matchedTransactions} Treffer ansehen</button></div>{rule.conflict&&<p className="mt-2 rounded-lg bg-red-50 p-2 text-xs font-semibold text-red-800">Konflikt: Derselbe Auslöser verweist auf unterschiedliche Kategorien und wird nicht automatisch angewendet.</p>}<div className="mt-3 flex gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={rule.enabled} disabled={!rule.editable} onChange={e=>setBankRules(rows=>rows.map(row=>row.id===rule.id?{...row,enabled:e.target.checked}:row))}/>Aktiv</label><label className="flex items-center gap-2"><input type="checkbox" checked={rule.shared} disabled={!rule.editable} onChange={e=>setBankRules(rows=>rows.map(row=>row.id===rule.id?{...row,shared:e.target.checked}:row))}/>Familienkonten</label></div></div><select disabled={!rule.editable} value={rule.categoryId} onChange={e=>setBankRules(rows=>rows.map(row=>row.id===rule.id?{...row,categoryId:e.target.value}:row))} className="min-h-11 min-w-0 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3"><CategorySelectOptions categories={categories}/></select>{rule.editable&&<div className="flex flex-wrap gap-2 lg:justify-end"><button disabled={busy===rule.id} onClick={()=>void saveBank(rule,false)} className="btn-secondary"><Save size={16}/>Künftig</button><button disabled={busy===rule.id} onClick={()=>void saveBank(rule,true)} className="btn-primary"><RefreshCw size={16}/>Rückwirkend</button><button disabled={busy===rule.id} onClick={()=>void remove("bank",rule.id,rule.displayValue)} className="btn-secondary text-red-700" aria-label="Regel löschen"><Trash2 size={16}/></button></div>}</article>)}{!bankRules.length&&<p className="p-6 text-sm muted">Noch keine bestätigten Bankregeln vorhanden.</p>}</div></section>
  <section className="card overflow-hidden"><header className="flex flex-col justify-between gap-3 border-b border-[var(--border)] p-5 sm:flex-row sm:items-center"><div><h2 className="font-bold">Amazon-Artikelregeln</h2><p className="mt-1 text-sm muted">{amazonRules.length} Regeln · exakte Artikelnamen und Platzhalter</p></div><Link href="/einstellungen/amazon-regeln" className="btn-secondary"><PackageSearch size={17}/>Artikelmatrix öffnen</Link></header><div className="divide-y divide-[var(--border)]">{amazonRules.map(rule=><article key={rule.id} className="grid gap-3 p-4 md:grid-cols-[1fr_280px_auto] md:items-center"><code className="break-all font-semibold">{rule.pattern}</code><select value={rule.categoryId} onChange={event=>void saveAmazon(rule,event.target.value)} className="min-h-11 min-w-0 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3"><CategorySelectOptions categories={expenseCategories}/></select><button disabled={busy===rule.id} onClick={()=>void remove("amazon",rule.id,rule.pattern)} className="btn-secondary text-red-700" aria-label="Amazon-Regel löschen"><Trash2 size={16}/></button></article>)}{!amazonRules.length&&<p className="p-6 text-sm muted">Noch keine Amazon-Artikelregeln vorhanden. In der Artikelmatrix kannst du exakte Regeln und Platzhalter anlegen.</p>}</div></section>
  <section className="grid gap-4 md:grid-cols-2"><article className="card p-5"><BookOpenCheck className="text-[var(--primary)]"/><h2 className="mt-3 font-bold">Sichere Systemerkennung</h2><p className="mt-2 text-sm leading-6 muted">Bekannte Abos, Kontogebühren, Lebensmittelmärkte, Telekommunikation, Tankstellen und eindeutige Einnahmen werden lokal erkannt. Diese Grundlogik erzeugt keine neuen Kategorien und läuft nur auf offenen Umsätzen.</p></article><article className="card p-5"><RefreshCw className="text-[var(--primary)]"/><h2 className="mt-3 font-bold">Abos & regelmäßige Zahlungen</h2><p className="mt-2 text-sm leading-6 muted">Wiederkehrende Kosten sind eine Auswertung der Buchungsfolgen, keine zusätzliche Kategorie-Regel. Deshalb bleiben Kündbarkeit, Rhythmus und Preisänderung in einer eigenen Analyse.</p><Link href="/einstellungen/wiederkehrend" className="btn-secondary mt-4">Wiederkehrende Kosten ansehen</Link></article></section>
  {referenceRule&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/45 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="automation-reference-title"><section className="max-h-[88dvh] w-full overflow-hidden rounded-t-2xl bg-[var(--surface)] shadow-2xl sm:max-w-3xl sm:rounded-2xl"><header className="flex items-start justify-between gap-4 border-b border-[var(--border)] p-5"><div><h2 id="automation-reference-title" className="text-lg font-bold">Passende Buchungen</h2><p className="mt-1 break-words text-sm muted">Referenzen für „{referenceRule.displayValue}“ · {referenceTotal} Treffer</p></div><button onClick={()=>setReferenceRule(null)} className="btn-secondary !min-h-10 !px-3" aria-label="Schließen"><X size={18}/></button></header><div className="max-h-[68dvh] overflow-y-auto p-4 sm:p-5">{referenceBusy?<p className="py-10 text-center muted">Buchungen werden geladen …</p>:<div className="space-y-3">{references.map(tx=><article key={tx.id} className="rounded-xl border border-[var(--border)] p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{new Intl.DateTimeFormat("de-DE").format(new Date(`${tx.bookedOn}T12:00:00`))} · {tx.counterparty??"Unbekannt"}</strong><strong>{Number(tx.amount).toLocaleString("de-DE",{style:"currency",currency:tx.currency})}</strong></div><p className="mt-2 break-words text-sm muted">{tx.purpose||"Kein Buchungstext"}</p><p className="mt-2 text-xs muted">{tx.accountName} · {tx.categoryName??"Nicht zugeordnet"}</p></article>)}</div>}</div></section></div>}
 </div>
}
