"use client";
import {FormEvent,useEffect,useState} from "react";
import {Building2,CheckCircle2,ChevronRight,Download,Eye,EyeOff,HelpCircle,LoaderCircle,LockKeyhole,Search,ShieldCheck} from "lucide-react";
import {PageHeader} from "@/components/page-header";
type Method={id:number;name:string;isDecoupled:boolean;media:string[];mediaRequired:boolean};
type BankAccount={accountNumber:string;iban:string|null;currency:string;holder:string;product:string;type:string};
type LocalAccount={id:string;name:string;kind:string;ibanLast4:string|null};
type Status={configured:boolean;connection?:{blz?:string;ibanLast4?:string;bankProduct?:string};localAccounts:LocalAccount[]};

export default function SparkasseSetup(){
 const[status,setStatus]=useState<Status|null>(null),[stage,setStage]=useState<"credentials"|"method"|"tan"|"accounts"|"done">("credentials"),[token,setToken]=useState(""),[methods,setMethods]=useState<Method[]>([]),[bankAccounts,setBankAccounts]=useState<BankAccount[]>([]),[methodId,setMethodId]=useState(""),[media,setMedia]=useState(""),[bankAccount,setBankAccount]=useState(""),[localAccount,setLocalAccount]=useState(""),[tan,setTan]=useState(""),[challenge,setChallenge]=useState(""),[decoupled,setDecoupled]=useState(false),[showPin,setShowPin]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const[syncBusy,setSyncBusy]=useState(false),[syncToken,setSyncToken]=useState(""),[syncTan,setSyncTan]=useState(""),[syncChallenge,setSyncChallenge]=useState(""),[syncDecoupled,setSyncDecoupled]=useState(false),[syncResult,setSyncResult]=useState<{imported:number;duplicates:number;locallyCategorized:number}|null>(null);
 const[reconfigure,setReconfigure]=useState(false);
 const[blz,setBlz]=useState(""),[endpoint,setEndpoint]=useState(""),[bankHint,setBankHint]=useState(""),[lookupBusy,setLookupBusy]=useState(false);
 useEffect(()=>{fetch("/api/fints/sparkasse/setup").then(r=>r.json()).then(setStatus)},[]);
 async function call(body:object){setBusy(true);setError("");try{const r=await fetch("/api/fints/sparkasse/setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await r.json();if(!r.ok)throw new Error(data.error);if(data.token)setToken(data.token);if(data.stage==="tan_method"){setMethods(data.methods);setMethodId(String(data.methods[0]?.id??""));setStage("method")}if(data.stage==="tan"){setChallenge(data.challenge);setDecoupled(data.isDecoupled);setStage("tan")}if(data.stage==="accounts"){setBankAccounts(data.accounts);setBankAccount(data.accounts[0]?.accountNumber??"");setLocalAccount(status?.localAccounts[0]?.id??"");setStage("accounts")}if(data.ok){const refreshed=await fetch("/api/fints/sparkasse/setup").then(response=>response.json());setStatus(refreshed);setReconfigure(false);setStage("credentials")}}catch(e){setError(e instanceof Error?e.message:"Verbindung fehlgeschlagen.")}finally{setBusy(false)}}
 async function discover(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await call({action:"discover",productId:f.get("productId"),endpoint,blz,userId:f.get("userId"),pin:f.get("pin")})}
 async function lookupEndpoint(){if(!/^\d{8}$/.test(blz))return;setLookupBusy(true);setBankHint("");try{const response=await fetch(`/api/fints/sparkasse/directory?blz=${encodeURIComponent(blz)}`),body=await response.json();if(!response.ok)throw new Error(body.error);setEndpoint(body.bank.endpoint);setBankHint(`${body.bank.name}${body.bank.city?` · ${body.bank.city}`:""} · FinTS-Adresse übernommen`) }catch(reason){setBankHint(reason instanceof Error?reason.message:"FinTS-Adresse konnte nicht ermittelt werden.")}finally{setLookupBusy(false)}}
 async function synchronize(action:"start"|"continue_tan"){setSyncBusy(true);setError("");try{const r=await fetch("/api/fints/sparkasse/sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(action==="start"?{action,days:90}:{action,token:syncToken,tan:syncTan||undefined})}),data=await r.json();if(!r.ok)throw new Error(data.error);if(data.requiresTan){setSyncToken(data.token);setSyncChallenge(data.challenge??"Bitte den Abruf bei deiner Sparkasse freigeben.");setSyncDecoupled(Boolean(data.isDecoupled))}else{setSyncToken("");setSyncTan("");setSyncResult(data)}}catch(e){setError(e instanceof Error?e.message:"Umsätze konnten nicht abgerufen werden.")}finally{setSyncBusy(false)}}
 const selected=methods.find(item=>String(item.id)===methodId);
 if(status?.configured&&stage==="credentials"&&!reconfigure)return <div className="space-y-7"><PageHeader eyebrow="Einstellungen · Bankverbindung" title="Sparkasse verbunden" description="Rufe neue Umsätze ab oder richte die Verbindung bei geänderten Zugangsdaten erneut ein."/>{error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-900">{error}</div>}<section className="card space-y-5 p-5 sm:p-7"><div><h2 className="text-xl font-bold">{status.connection?.bankProduct??"Sparkassenkonto"}</h2><p className="mt-1 text-sm muted">BLZ {status.connection?.blz} · IBAN •••• {status.connection?.ibanLast4}</p></div>{syncResult&&<div className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900"><strong>Abruf abgeschlossen:</strong> {syncResult.imported} neue Umsätze, {syncResult.duplicates} bereits vorhanden und {syncResult.locallyCategorized} durch sichere Regeln zugeordnet.</div>}{syncToken?<div className="space-y-3"><div className="rounded-xl bg-[var(--surface-soft)] p-4 text-sm">{syncChallenge}</div>{syncDecoupled?<p className="text-sm">Bestätige den lesenden Abruf in deiner Sparkassen-/pushTAN-App.</p>:<input aria-label="TAN" value={syncTan} onChange={event=>setSyncTan(event.target.value)} className="input" inputMode="numeric" placeholder="TAN eingeben"/>}<button className="btn-primary" disabled={syncBusy||(!syncDecoupled&&!syncTan)} onClick={()=>synchronize("continue_tan")}>{syncBusy&&<LoaderCircle className="animate-spin" size={17}/>} {syncDecoupled?"Freigabe prüfen":"TAN bestätigen"}</button></div>:<div className="flex flex-wrap gap-3"><button className="btn-primary" disabled={syncBusy} onClick={()=>synchronize("start")}>{syncBusy?<LoaderCircle className="animate-spin" size={17}/>:<Download size={17}/>}Letzte 90 Tage abrufen</button><button className="btn-secondary" onClick={()=>{setSyncResult(null);setReconfigure(true)}}>Zugangsdaten neu einrichten</button></div>}<p className="text-xs leading-5 muted">Dubletten und Nullbuchungen werden nicht angelegt. Anschließend laufen gelernte Regeln automatisch; nur die verbleibende Restmenge muss geprüft werden.</p></section></div>;
 return <div className="space-y-7"><PageHeader eyebrow="Einstellungen · Bankverbindung" title="Sparkasse lesend verbinden" description="Konten und Umsätze direkt über FinTS abrufen – ohne Überweisungsfunktion und ohne Weitergabe an die KI."/>
  <section className="grid gap-4 md:grid-cols-3">{[[ShieldCheck,"Nur lesen","Die Integration enthält technisch keine Zahlungs- oder Überweisungsfunktion."],[LockKeyhole,"Lokal verschlüsselt","PIN und Bankparameter werden mit dem Schlüssel deines LXC verschlüsselt."],[Building2,"Direkt zur Sparkasse","FinTS kommuniziert vom LXC unmittelbar mit dem Bankserver."]].map(([Icon,title,text])=><article className="card p-5" key={title as string}><Icon className="text-[var(--primary)]"/><h2 className="mt-3 font-bold">{title as string}</h2><p className="mt-1 text-sm muted">{text as string}</p></article>)}</section>
  {error&&<div role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-900">{error}</div>}
  <section className="card p-5 sm:p-7"><div className="mb-6 flex flex-wrap items-center gap-2 text-sm font-semibold">{["Zugang","TAN-Verfahren","Konto wählen","Fertig"].map((name,index)=><span key={name} className={`rounded-full px-3 py-1 ${index<(["credentials","method","tan","accounts","done"].indexOf(stage)+1)?"bg-[var(--primary)] text-white":"bg-[var(--surface-soft)]"}`}>{index+1}. {name}</span>)}</div>
  {stage==="credentials"&&<form onSubmit={discover} className="space-y-5"><h2 className="text-xl font-bold">FinTS-Zugangsdaten</h2><Field label="FinTS-Produkt-ID" help="Diese ID gehört zur Finanzplaner-Software, nicht zu deinem Konto. Der Administrator registriert sie einmal kostenlos bei der Deutschen Kreditwirtschaft." link="https://www.fints.org/de/hersteller/produktregistrierung"><input required name="productId" className="input" placeholder="Von FinTS vergebene Produkt-ID"/></Field><Field label="BLZ deiner Sparkasse" help="Die achtstellige Bankleitzahl steht auf Kontoauszügen, in der Sparkassen-App bei den Kontodetails oder auf der Website deiner Sparkasse."><div className="flex flex-col gap-2 sm:flex-row"><input required name="blz" value={blz} onChange={event=>{setBlz(event.target.value.replace(/\D/g,"").slice(0,8));setEndpoint("");setBankHint("")}} inputMode="numeric" pattern="[0-9]{8}" maxLength={8} className="input min-w-0 flex-1" placeholder="Zum Beispiel 76550000"/><button type="button" disabled={lookupBusy||!/^\d{8}$/.test(blz)} onClick={lookupEndpoint} className="btn-secondary shrink-0">{lookupBusy?<LoaderCircle className="animate-spin" size={17}/>:<Search size={17}/>}Adresse ermitteln</button></div>{bankHint&&<span role="status" className={`mt-2 block text-xs ${endpoint?"text-emerald-700":"text-amber-700"}`}>{bankHint}</span>}</Field><Field label="FinTS-Adresse" help="Die App ermittelt die PIN/TAN-Adresse aus der BLZ. Falls deine Sparkasse dort fehlt, kannst du ihre offizielle HTTPS-Adresse weiterhin manuell eintragen."><input required name="endpoint" value={endpoint} onChange={event=>{setEndpoint(event.target.value);setBankHint("")}} type="url" pattern="https://.*" className="input" placeholder="Wird nach Eingabe der BLZ automatisch übernommen"/></Field><Field label="Anmeldename oder Legitimations-ID" help="Verwende denselben Anmeldenamen wie im Sparkassen-Online-Banking. Nicht die IBAN und nicht die Kartennummer."><input required name="userId" autoComplete="username" className="input"/></Field><Field label="Online-Banking-PIN" help="Die PIN wird nur verschlüsselt im lokalen Finanzplaner gespeichert und direkt an die Sparkasse übertragen. Sie geht niemals an OpenAI oder Gemini."><div className="relative"><input required name="pin" type={showPin?"text":"password"} autoComplete="current-password" className="input pr-12"/><button type="button" onClick={()=>setShowPin(v=>!v)} className="absolute right-2 top-1/2 -translate-y-1/2 p-2" aria-label="PIN anzeigen oder verbergen">{showPin?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></Field><button disabled={busy} className="btn-primary">{busy?<LoaderCircle className="animate-spin" size={17}/>:<ChevronRight size={17}/>}Verbindung sicher prüfen</button></form>}
  {stage==="method"&&<div className="space-y-5"><h2 className="text-xl font-bold">TAN-Verfahren auswählen</h2><p className="text-sm muted">Diese Verfahren hat deine Sparkasse für den Zugang gemeldet.</p><select className="input" value={methodId} onChange={e=>{setMethodId(e.target.value);setMedia("")}}>{methods.map(item=><option key={item.id} value={item.id}>{item.name}{item.isDecoupled?" · Freigabe per App":""}</option>)}</select>{selected&&selected.media.length>0&&<select className="input" value={media} onChange={e=>setMedia(e.target.value)} required={selected.mediaRequired}><option value="">TAN-Gerät auswählen</option>{selected.media.map(name=><option key={name}>{name}</option>)}</select>}<button disabled={busy||!methodId||(selected?.mediaRequired&&!media)} onClick={()=>call({action:"select_method",token,tanMethodId:Number(methodId),tanMediaName:media||undefined})} className="btn-primary">Weiter</button></div>}
  {stage==="tan"&&<div className="space-y-5"><h2 className="text-xl font-bold">Zugriff bei der Sparkasse bestätigen</h2><div className="rounded-xl bg-[var(--surface-soft)] p-4 text-sm">{challenge}</div>{decoupled?<p className="text-sm">Öffne jetzt deine Sparkassen-/pushTAN-App und bestätige den ausschließlich lesenden Zugriff. Klicke danach auf „Freigabe prüfen“.</p>:<input value={tan} onChange={e=>setTan(e.target.value)} className="input" inputMode="numeric" placeholder="TAN eingeben"/>}<button disabled={busy||(!decoupled&&!tan)} onClick={()=>call({action:"continue_tan",token,tan:tan||undefined})} className="btn-primary">{decoupled?"Freigabe prüfen":"TAN bestätigen"}</button></div>}
  {stage==="accounts"&&<div className="space-y-5"><h2 className="text-xl font-bold">Sparkassenkonto zuordnen</h2><p className="text-sm muted">Ordne das gefundene Bankkonto dem bereits im Finanzplaner angelegten Konto zu.</p><Field label="Bei der Sparkasse gefunden" help="Nur dieses Konto wird später gelesen."><select className="input" value={bankAccount} onChange={e=>setBankAccount(e.target.value)}>{bankAccounts.map(a=><option key={a.accountNumber} value={a.accountNumber}>{a.product} · {a.holder} · {a.iban??a.accountNumber}</option>)}</select></Field><Field label="Konto im Finanzplaner" help="Umsätze werden in dieses lokale Konto importiert. Die IBAN-Endziffern sollten übereinstimmen."><select className="input" value={localAccount} onChange={e=>setLocalAccount(e.target.value)}><option value="">Lokales Konto auswählen</option>{status?.localAccounts.map(a=><option key={a.id} value={a.id}>{a.name}{a.ibanLast4?` · •••• ${a.ibanLast4}`:""}</option>)}</select></Field>{!status?.localAccounts.length&&<p className="text-sm text-amber-800">Lege zuerst unter „Konten“ ein Konto an.</p>}<button disabled={busy||!bankAccount||!localAccount} onClick={()=>call({action:"save",token,bankAccountNumber:bankAccount,localAccountId:localAccount})} className="btn-primary">Verbindung speichern</button></div>}
  {stage==="done"&&<div className="py-8 text-center"><CheckCircle2 size={48} className="mx-auto text-emerald-600"/><h2 className="mt-4 text-2xl font-bold">Sparkasse ist verbunden</h2><p className="mt-2 muted">Die Verbindung wurde verschlüsselt gespeichert. Lade die Seite neu und rufe anschließend die letzten 90 Tage ab.</p></div>}
  </section></div>
}
function Field({label,help,link,children}:{label:string;help:string;link?:string;children:React.ReactNode}){return <label className="block"><span className="flex items-center gap-2 font-semibold">{label}<span title={help}><HelpCircle size={16} className="muted"/></span></span><span className="mb-2 mt-1 block text-xs leading-5 muted">{help}{link&&<> <a href={link} target="_blank" rel="noreferrer" className="font-semibold text-[var(--primary)]">Anleitung öffnen</a></>}</span>{children}</label>}
